'use strict';/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var yg=function(a,b,c){a.timeOfStartCall=(new Date).getTime();var d=c||Fa,e=d.document,f=a.nonce||Ia(d);f&&!a.nonce&&(a.nonce=f);if("help"==a.flow){var g=Ka("document.location.href",d);!a.helpCenterContext&&g&&(a.helpCenterContext=g.substring(0,1200));g=!0;if(b&&JSON&&JSON.stringify){var h=JSON.stringify(b);(g=1200>=h.length)&&(a.psdJson=h)}g||(b={invalidPsd:!0})}b=[a,b,c];d.GOOGLE_FEEDBACK_START_ARGUMENTS=b;c=a.serverUri||"//www.google.com/tools/feedback";if(g=d.GOOGLE_FEEDBACK_START)g.apply(d,b);
else{d=c+"/load.js?";for(var m in a)b=a[m],null==b||Ra(b)||(d+=encodeURIComponent(m)+"="+encodeURIComponent(b)+"&");a=wg(lg(e),"SCRIPT");f&&a.setAttribute("nonce",f);f=ld(d);we(a,f);e.body.appendChild(a)}};v("userfeedback.api.startFeedback",yg);var zg=function(){this.j=this.h=this.u=this.modelName=this.l=this.g=this.Kc="";this.o=this.D=this.m=!1};var Ag=chrome.i18n.getMessage("4163185390680253103"),Bg=chrome.i18n.getMessage("492097680647953484"),Cg=chrome.i18n.getMessage("2575016469622936324"),Dg=chrome.i18n.getMessage("128276876460319075"),Eg=chrome.i18n.getMessage("3326722026796849289"),Fg=chrome.i18n.getMessage("1018984561488520517"),Gg=chrome.i18n.getMessage("8205999658352447129"),Hg=chrome.i18n.getMessage("5723583529370342957"),Ig=chrome.i18n.getMessage("1550904064710828958"),Jg=chrome.i18n.getMessage("5014364904504073524"),Kg=chrome.i18n.getMessage("2194670894476780934"),
Lg=chrome.i18n.getMessage("6614468912728530636"),Mg=chrome.i18n.getMessage("5910595154486533449"),Ng=chrome.i18n.getMessage("5363086287710390513"),Og=chrome.i18n.getMessage("244647017322945605"),Pg=chrome.i18n.getMessage("5375576275991472719"),Qg=chrome.i18n.getMessage("4592127349908255218"),Rg=chrome.i18n.getMessage("843316808366399491"),Sg=chrome.i18n.getMessage("5699813974548050528"),Tg=chrome.i18n.getMessage("8515148417333877999"),Ug=chrome.i18n.getMessage("1636686747687494376"),Vg=chrome.i18n.getMessage("4148300086676792937"),
Wg=chrome.i18n.getMessage("3219866268410307919"),Xg=chrome.i18n.getMessage("9211708838274008657"),Yg=chrome.i18n.getMessage("8706273405040403641"),Zg=chrome.i18n.getMessage("4756056595565370923"),$g=chrome.i18n.getMessage("7876724262035435114"),ah=chrome.i18n.getMessage("5485620192329479690"),bh=chrome.i18n.getMessage("6963873398546068901"),ch=chrome.i18n.getMessage("3567591856726172993"),dh=chrome.i18n.getMessage("3239956785410157548");var eh={"* ARIA-CHECKED":!0,"* ARIA-COLCOUNT":!0,"* ARIA-COLINDEX":!0,"* ARIA-CONTROLS":!0,"* ARIA-DESCRIBEDBY":!0,"* ARIA-DISABLED":!0,"* ARIA-EXPANDED":!0,"* ARIA-GOOG-EDITABLE":!0,"* ARIA-HASPOPUP":!0,"* ARIA-HIDDEN":!0,"* ARIA-LABEL":!0,"* ARIA-LABELLEDBY":!0,"* ARIA-MULTILINE":!0,"* ARIA-MULTISELECTABLE":!0,"* ARIA-ORIENTATION":!0,"* ARIA-PLACEHOLDER":!0,"* ARIA-READONLY":!0,"* ARIA-REQUIRED":!0,"* ARIA-ROLEDESCRIPTION":!0,"* ARIA-ROWCOUNT":!0,"* ARIA-ROWINDEX":!0,"* ARIA-SELECTED":!0,"* ABBR":!0,
"* ACCEPT":!0,"* ACCESSKEY":!0,"* ALIGN":!0,"* ALT":!0,"* AUTOCOMPLETE":!0,"* AXIS":!0,"* BGCOLOR":!0,"* BORDER":!0,"* CELLPADDING":!0,"* CELLSPACING":!0,"* CHAROFF":!0,"* CHAR":!0,"* CHECKED":!0,"* CLEAR":!0,"* COLOR":!0,"* COLSPAN":!0,"* COLS":!0,"* COMPACT":!0,"* COORDS":!0,"* DATETIME":!0,"* DIR":!0,"* DISABLED":!0,"* ENCTYPE":!0,"* FACE":!0,"* FRAME":!0,"* HEIGHT":!0,"* HREFLANG":!0,"* HSPACE":!0,"* ISMAP":!0,"* LABEL":!0,"* LANG":!0,"* MAX":!0,"* MAXLENGTH":!0,"* METHOD":!0,"* MULTIPLE":!0,
"* NOHREF":!0,"* NOSHADE":!0,"* NOWRAP":!0,"* OPEN":!0,"* READONLY":!0,"* REQUIRED":!0,"* REL":!0,"* REV":!0,"* ROLE":!0,"* ROWSPAN":!0,"* ROWS":!0,"* RULES":!0,"* SCOPE":!0,"* SELECTED":!0,"* SHAPE":!0,"* SIZE":!0,"* SPAN":!0,"* START":!0,"* SUMMARY":!0,"* TABINDEX":!0,"* TITLE":!0,"* TYPE":!0,"* VALIGN":!0,"* VALUE":!0,"* VSPACE":!0,"* WIDTH":!0},fh={"* USEMAP":!0,"* ACTION":!0,"* CITE":!0,"* HREF":!0,"* LONGDESC":!0,"* SRC":!0,"LINK HREF":!0,"* FOR":!0,"* HEADERS":!0,"* NAME":!0,"A TARGET":!0,
"* CLASS":!0,"* ID":!0,"* STYLE":!0};var gh={};
function hh(a){if(Me&&!gf(9))return[0,0,0,0];var b=gh.hasOwnProperty(a)?gh[a]:null;if(b)return b;65536<Object.keys(gh).length&&(gh={});var c=[0,0,0,0];b=ih(a,/\\[0-9A-Fa-f]{6}\s?/g);b=ih(b,/\\[0-9A-Fa-f]{1,5}\s/g);b=ih(b,/\\./g);b=b.replace(/:not\(([^\)]*)\)/g,"     $1 ");b=b.replace(/{[^]*/gm,"");b=jh(b,c,/(\[[^\]]+\])/g,2);b=jh(b,c,/(#[^\#\s\+>~\.\[:]+)/g,1);b=jh(b,c,/(\.[^\s\+>~\.\[:]+)/g,2);b=jh(b,c,/(::[^\s\+>~\.\[:]+|:first-line|:first-letter|:before|:after)/gi,3);b=jh(b,c,/(:[\w-]+\([^\)]*\))/gi,2);
b=jh(b,c,/(:[^\s\+>~\.\[:]+)/g,2);b=b.replace(/[\*\s\+>~]/g," ");b=b.replace(/[#\.]/g," ");jh(b,c,/([^\s\+>~\.\[:]+)/g,3);b=c;return gh[a]=b}function jh(a,b,c,d){return a.replace(c,function(e){b[d]+=1;return Array(e.length+1).join(" ")})}function ih(a,b){return a.replace(b,function(c){return Array(c.length+1).join("A")})};var kh={rgb:!0,rgba:!0,alpha:!0,rect:!0,image:!0,"linear-gradient":!0,"radial-gradient":!0,"repeating-linear-gradient":!0,"repeating-radial-gradient":!0,"cubic-bezier":!0,matrix:!0,perspective:!0,rotate:!0,rotate3d:!0,rotatex:!0,rotatey:!0,steps:!0,rotatez:!0,scale:!0,scale3d:!0,scalex:!0,scaley:!0,scalez:!0,skew:!0,skewx:!0,skewy:!0,translate:!0,translate3d:!0,translatex:!0,translatey:!0,translatez:!0},lh=/[\n\f\r"'()*<>]/g,mh={"\n":"%0a","\f":"%0c","\r":"%0d",'"':"%22","'":"%27","(":"%28",")":"%29",
"*":"%2a","<":"%3c",">":"%3e"};function nh(a){return mh[a]}
var oh=function(a,b,c){b=rd(b);if(""==b)return null;if(0==sd("url(",b.substr(0,4))){if(!b.endsWith(")")||1<(b?b.split("(").length-1:0)||1<(b?b.split(")").length-1:0)||!c)a=null;else{a:{b=b.substring(4,b.length-1);for(var d=0;2>d;d++){var e="\"'".charAt(d);if(b.charAt(0)==e&&b.charAt(b.length-1)==e){b=b.substring(1,b.length-1);break a}}}a=c?(a=c(b,a))&&"about:invalid#zClosurez"!=Fd(a)?'url("'+Fd(a).replace(lh,nh)+'")':null:null}return a}if(0<b.indexOf("(")){if(/"|'/.test(b))return null;for(a=/([\-\w]+)\(/g;c=
a.exec(b);)if(!(c[1].toLowerCase()in kh))return null}return b};function ph(a,b){a=Fa[a];return a&&a.prototype?(b=Object.getOwnPropertyDescriptor(a.prototype,b))&&b.get||null:null}function qh(a,b){return(a=Fa[a])&&a.prototype&&a.prototype[b]||null}
var rh=ph("Element","attributes")||ph("Node","attributes"),sh=qh("Element","hasAttribute"),th=qh("Element","getAttribute"),uh=qh("Element","setAttribute"),vh=qh("Element","removeAttribute"),wh=qh("Element","getElementsByTagName"),xh=qh("Element","matches")||qh("Element","msMatchesSelector"),yh=ph("Node","nodeName"),zh=ph("Node","nodeType"),Ah=ph("Node","parentNode"),Bh=ph("HTMLElement","style")||ph("Element","style"),Ch=ph("HTMLStyleElement","sheet"),Dh=qh("CSSStyleDeclaration","getPropertyValue"),
Eh=qh("CSSStyleDeclaration","setProperty");function Fh(a,b,c,d){if(a)return a.apply(b);a=b[c];if(!d(a))throw Error("Clobbering detected");return a}function Gh(a,b,c,d){if(a)return a.apply(b,d);if(Me&&10>document.documentMode){if(!b[c].call)throw Error("IE Clobbering detected");}else if("function"!=typeof b[c])throw Error("Clobbering detected");return b[c].apply(b,d)}function Hh(a){return Fh(rh,a,"attributes",function(b){return b instanceof NamedNodeMap})}
function Ih(a,b,c){try{Gh(uh,a,"setAttribute",[b,c])}catch(d){if(-1==d.message.indexOf("A security problem occurred"))throw d;}}function Jh(a){Kh(a);return Fh(Bh,a,"style",function(b){return b instanceof CSSStyleDeclaration})}function Kh(a){if(!(a instanceof HTMLElement))throw Error("Not an HTMLElement");}function Lh(a){Kh(a);return Fh(Ch,a,"sheet",function(b){return b instanceof CSSStyleSheet})}function Mh(a){return Fh(yh,a,"nodeName",function(b){return"string"==typeof b})}
function Nh(a){return Fh(zh,a,"nodeType",function(b){return"number"==typeof b})}function Oh(a){return Fh(Ah,a,"parentNode",function(b){return!(b&&"string"==typeof b.name&&b.name&&"parentnode"==b.name.toLowerCase())})}function Ph(a,b){return Gh(Dh,a,a.getPropertyValue?"getPropertyValue":"getAttribute",[b])||""}function Qh(a,b,c){Gh(Eh,a,a.setProperty?"setProperty":"setAttribute",[b,c])};var Rh=Me&&10>document.documentMode?null:/\s*([^\s'",]+[^'",]*(('([^'\r\n\f\\]|\\[^])*')|("([^"\r\n\f\\]|\\[^])*")|[^'",])*)/g,Sh={"-webkit-border-horizontal-spacing":!0,"-webkit-border-vertical-spacing":!0},Vh=function(a,b,c){var d=[];a=Th(ic(a.cssRules));Pb(a,function(e){if(b&&!/[a-zA-Z][\w-:\.]*/.test(b))throw Error("Invalid container id");if(!(b&&Me&&10==document.documentMode&&/\\['"]/.test(e.selectorText))){var f=b?e.selectorText.replace(Rh,"#"+b+" $1"):e.selectorText;d.push(Zd(f,Uh(e.style,
c)))}});return ae(d)},Th=function(a){return Rb(a,function(b){return b instanceof CSSStyleRule||b.type==CSSRule.STYLE_RULE})},Xh=function(a,b,c){a=Wh("<style>"+a+"</style>");return null==a||null==a.sheet?be:Vh(a.sheet,void 0!=b?b:null,c)},Wh=function(a){if(Me&&!gf(10)||"function"!=typeof Fa.DOMParser)return null;a=pe("<html><head></head><body>"+a+"</body></html>",null);return(new DOMParser).parseFromString(oe(a),"text/html").body.children[0]},Uh=function(a,b){if(!a)return Od;var c=document.createElement("div").style,
d=Yh(a);Pb(d,function(e){var f=Pe&&e in Sh?e:e.replace(/^-(?:apple|css|epub|khtml|moz|mso?|o|rim|wap|webkit|xv)-(?=[a-z])/i,"");od(f,"--")||od(f,"var")||(e=Ph(a,e),e=oh(f,e,b),null!=e&&Qh(c,f,e))});return new Md(c.cssText||"",Ld)},$h=function(a){var b=Array.from(Gh(wh,a,"getElementsByTagName",["STYLE"])),c=uc(b,function(e){return ic(Lh(e).cssRules)});c=Th(c);c.sort(function(e,f){e=hh(e.selectorText);a:{f=hh(f.selectorText);for(var g=nc,h=Math.min(e.length,f.length),m=0;m<h;m++){var q=g(e[m],f[m]);
if(0!=q){e=q;break a}}e=nc(e.length,f.length)}return-e});a=document.createTreeWalker(a,NodeFilter.SHOW_ELEMENT,null,!1);for(var d;d=a.nextNode();)Pb(c,function(e){Gh(xh,d,d.matches?"matches":"msMatchesSelector",[e.selectorText])&&e.style&&Zh(d,e.style)});Pb(b,ug)},Zh=function(a,b){var c=Yh(a.style),d=Yh(b);Pb(d,function(e){if(!(0<=c.indexOf(e))){var f=Ph(b,e);Qh(a.style,e,f)}})},Yh=function(a){Pa(a)?a=ic(a):(a=Ic(a),ec(a,"cssText"));return a};var ai="undefined"!=typeof WeakMap&&-1!=WeakMap.toString().indexOf("[native code]"),bi=0,ci=function(){this.j=[];this.h=[];this.g="data-elementweakmap-index-"+bi++};ci.prototype.set=function(a,b){if(Gh(sh,a,"hasAttribute",[this.g])){var c=parseInt(Gh(th,a,"getAttribute",[this.g])||null,10);this.h[c]=b}else c=this.h.push(b)-1,Ih(a,this.g,c.toString()),this.j.push(a);return this};
ci.prototype.get=function(a){if(Gh(sh,a,"hasAttribute",[this.g]))return a=parseInt(Gh(th,a,"getAttribute",[this.g])||null,10),this.h[a]};ci.prototype.clear=function(){this.j.forEach(function(a){Gh(vh,a,"removeAttribute",[this.g])},this);this.j=[];this.h=[]};var di=cg("goog.html.sanitizer.SafeDomTreeProcessor"),ei=!Me||10<=Number(kf),fi=!Me||null==document.documentMode,gi=function(){};var hi={APPLET:!0,AUDIO:!0,BASE:!0,BGSOUND:!0,EMBED:!0,FORM:!0,IFRAME:!0,ISINDEX:!0,KEYGEN:!0,LAYER:!0,LINK:!0,META:!0,OBJECT:!0,SCRIPT:!0,SVG:!0,STYLE:!0,TEMPLATE:!0,VIDEO:!0};var ii={A:!0,ABBR:!0,ACRONYM:!0,ADDRESS:!0,AREA:!0,ARTICLE:!0,ASIDE:!0,B:!0,BDI:!0,BDO:!0,BIG:!0,BLOCKQUOTE:!0,BR:!0,BUTTON:!0,CAPTION:!0,CENTER:!0,CITE:!0,CODE:!0,COL:!0,COLGROUP:!0,DATA:!0,DATALIST:!0,DD:!0,DEL:!0,DETAILS:!0,DFN:!0,DIALOG:!0,DIR:!0,DIV:!0,DL:!0,DT:!0,EM:!0,FIELDSET:!0,FIGCAPTION:!0,FIGURE:!0,FONT:!0,FOOTER:!0,FORM:!0,H1:!0,H2:!0,H3:!0,H4:!0,H5:!0,H6:!0,HEADER:!0,HGROUP:!0,HR:!0,I:!0,IMG:!0,INPUT:!0,INS:!0,KBD:!0,LABEL:!0,LEGEND:!0,LI:!0,MAIN:!0,MAP:!0,MARK:!0,MENU:!0,METER:!0,NAV:!0,
NOSCRIPT:!0,OL:!0,OPTGROUP:!0,OPTION:!0,OUTPUT:!0,P:!0,PRE:!0,PROGRESS:!0,Q:!0,S:!0,SAMP:!0,SECTION:!0,SELECT:!0,SMALL:!0,SOURCE:!0,SPAN:!0,STRIKE:!0,STRONG:!0,STYLE:!0,SUB:!0,SUMMARY:!0,SUP:!0,TABLE:!0,TBODY:!0,TD:!0,TEXTAREA:!0,TFOOT:!0,TH:!0,THEAD:!0,TIME:!0,TR:!0,TT:!0,U:!0,UL:!0,VAR:!0,WBR:!0};var ji={"ANNOTATION-XML":!0,"COLOR-PROFILE":!0,"FONT-FACE":!0,"FONT-FACE-SRC":!0,"FONT-FACE-URI":!0,"FONT-FACE-FORMAT":!0,"FONT-FACE-NAME":!0,"MISSING-GLYPH":!0},ni=function(a){a=a||new ki;li(a);this.g=Nc(a.g);this.m=Nc(a.F);this.j=Nc(a.H);this.u=a.C;Pb(a.o,function(b){if(!od(b,"data-"))throw new Ib('Only "data-" attributes allowed, got: %s.',[b]);if(od(b,"data-sanitizer-"))throw new Ib('Attributes with "%s" prefix are not allowed, got: %s.',["data-sanitizer-",b]);this.g["* "+b.toUpperCase()]=mi},
this);Pb(a.D,function(b){b=b.toUpperCase();if(-1==b.indexOf("-")||ji[b])throw new Ib("Only valid custom element tag names allowed, got: %s.",[b]);this.j[b]=!0},this);this.o=a.j;this.l=a.G;this.h=null;this.D=a.u};w(ni,gi);
var oi=function(a){return function(b,c){return(b=a(rd(b),c))&&"about:invalid#zClosurez"!=Fd(b)?Fd(b):null}},ki=function(){this.g={};Pb([eh,fh],function(a){Pb(Ic(a),function(b){this.g[b]=mi},this)},this);this.h={};this.o=[];this.D=[];this.F=Nc(hi);this.H=Nc(ii);this.C=!1;this.X=Kd;this.M=this.m=this.J=this.j=xc;this.G=null;this.l=this.u=!1},pi=function(a,b){return function(c,d,e,f){c=a(c,d,e,f);return null==c?null:b(c,d,e,f)}},qi=function(a,b,c,d){a[c]&&!b[c]&&(a[c]=pi(a[c],d))};ki.prototype.ha=function(){return new ni(this)};
var li=function(a){if(a.l)throw Error("HtmlSanitizer.Builder.build() can only be used once.");qi(a.g,a.h,"* USEMAP",ri);var b=oi(a.X);Pb(["* ACTION","* CITE","* HREF"],function(d){qi(this.g,this.h,d,b)},a);var c=oi(a.j);Pb(["* LONGDESC","* SRC","LINK HREF"],function(d){qi(this.g,this.h,d,c)},a);Pb(["* FOR","* HEADERS","* NAME"],function(d){qi(this.g,this.h,d,Za(si,this.J))},a);qi(a.g,a.h,"A TARGET",Za(ti,["_blank","_self"]));qi(a.g,a.h,"* CLASS",Za(ui,a.m));qi(a.g,a.h,"* ID",Za(vi,a.m));qi(a.g,a.h,
"* STYLE",Za(a.M,c));a.l=!0},wi=function(a,b){a||(a="*");return(a+" "+b).toUpperCase()},mi=function(a){return rd(a)},ti=function(a,b){b=rd(b);return Zb(a,b.toLowerCase())?b:null},ri=function(a){return(a=rd(a))&&"#"==a.charAt(0)?a:null},si=function(a,b,c){return a(rd(b),c)},ui=function(a,b,c){b=b.split(/(?:\s+)/);for(var d=[],e=0;e<b.length;e++){var f=a(b[e],c);f&&d.push(f)}return 0==d.length?null:d.join(" ")},vi=function(a,b,c){return a(rd(b),c)},xi=function(a,b){var c=b.data;(b=Oh(b))&&"style"==
Mh(b).toLowerCase()&&!("STYLE"in a.m)&&"STYLE"in a.j&&(c=$d(Xh(c,a.h,Ya(function(d,e){return this.o(d,{bN:e})},a))));return document.createTextNode(c)},yi=function(a){var b=(new ki).ha();var c=!("STYLE"in b.m)&&"STYLE"in b.j;c="*"==b.l&&c?"sanitizer-"+Ce():b.l;b.h=c;if(ei){c=a;if(ei){a=sg(document,"SPAN");b.h&&"*"==b.l&&(a.id=b.h);b.D&&(c=Wh("<div>"+c+"</div>"),$h(c),c=c.innerHTML);c=pe(c,null);var d=document.createElement("template");if(fi&&"content"in d)ue(d,c),d=d.content;else{var e=document.implementation.createHTMLDocument("x");
d=e.body;ue(e.body,c)}c=document.createTreeWalker(d,NodeFilter.SHOW_ELEMENT|NodeFilter.SHOW_TEXT,null,!1);for(d=ai?new WeakMap:new ci;e=c.nextNode();){c:{var f=b;var g=e;var h=Nh(g);switch(h){case 3:g=xi(f,g);break c;case 1:h=g;1==Nh(h)||Mb("Expected Node of type Element but got Node of type %s",Nh(h));g=f;f=h;if("TEMPLATE"==Mh(f).toUpperCase())g=null;else{h=Mh(f).toUpperCase();if(h in g.m)var m=null;else g.j[h]?m=document.createElement(h):(m=sg(document,"SPAN"),g.u&&Ih(m,"data-sanitizer-original-tag",
h.toLowerCase()));if(m){var q=m,r=Hh(f);if(null!=r)for(var y=0;h=r[y];y++)if(h.specified){var C=g;var A=f,F=h,L=F.name;if(od(L,"data-sanitizer-"))C=null;else{var ha=Mh(A);F=F.value;var Na={tagName:rd(ha).toLowerCase(),attributeName:rd(L).toLowerCase()},sb={Es:void 0};"style"==Na.attributeName&&(sb.Es=Jh(A));A=wi(ha,L);A in C.g?(C=C.g[A],C=C(F,Na,sb)):(L=wi(null,L),L in C.g?(C=C.g[L],C=C(F,Na,sb)):C=null)}null!==C&&Ih(q,h.name,C)}g=m}else g=null}break c;default:fg(di,"Dropping unknown node type: "+
h),g=null}}if(g){if(1==Nh(g)&&d.set(e,g),e=Oh(e),f=!1,e)h=Nh(e),m=Mh(e).toLowerCase(),q=Oh(e),11!=h||q?"body"==m&&q&&(h=Oh(q))&&!Oh(h)&&(f=!0):f=!0,h=null,f||!e?h=a:1==Nh(e)&&(h=d.get(e)),h.content&&(h=h.content),h.appendChild(g)}else tg(e)}d.clear&&d.clear();b=a}else b=sg(document,"SPAN");0<Hh(b).length&&(a=sg(document,"SPAN"),a.appendChild(b),b=a);b=(new XMLSerializer).serializeToString(b);b=b.slice(b.indexOf(">")+1,b.lastIndexOf("</"))}else b="";return pe(b,null)};if("undefined"!=typeof angular){var zi=angular.module("chrome_18n",[]);chrome.runtime&&chrome.runtime.getManifest&&chrome.runtime.getManifest().default_locale&&zi.directive("angularMessage",function(){return{restrict:"E",replace:!0,controller:["$scope",function(a){var b=this;this.bj=this.Cg=null;a.dirForText=function(c){b.Cg||(b.Cg=chrome.i18n.getMessage("@@bidi_dir")||"ltr");b.bj||(b.bj=new xg("rtl"==b.Cg));var d=b.bj,e,f=e=0,g=!1;c=(c||"").split(ed);for(var h=0;h<c.length;h++){var m=c[h];cd.test(m)?
(e++,f++):dd.test(m)?g=!0:bd.test(m)?f++:fd.test(m)&&(g=!0)}e=0==f?g?1:0:.4<e/f?-1:1;return-1==(0==e?d.g:e)?"rtl":"ltr"}}],compile:function(a,b){b=b.key;var c=null,d=document.createElement("amr");b&&!b.match(/^\d+$/)&&(b=chrome.i18n.getMessage(b),null==b&&d.setAttribute("id","missing"));if(b){var e=chrome.i18n.getMessage(b+"_ph");c=[];if(null!=e)for(c=e.split("\ue000"),e=0;e<c.length;++e)c[e]=c[e].replace(/^{{(.*)}}$/,'<amrp dir="{{dirForText($1)}}">{{$1}}</amrp>');c=chrome.i18n.getMessage(b,c)}else d.setAttribute("r",
"nokey");c?ve(d,yi(c)):(d.setAttribute("tl","false"),ve(d,yi(a.html())));a.replaceWith(d)}}})};var Bi=function(a,b){var c=this;this.D=b;this.g=a;this.g.top=a;this.o=[];this.l=!1;this.h=new zg;this.g.videoSmoothnessRatings=this.vl(Kg,Fg,Gg,Hg,Ig,Jg);this.g.videoQualityRatings=this.vl(Kg,Lg,Mg,Ng,Og,Pg);this.g.audioQualityRatings=this.vl(Kg,Qg,Rg,Sg,Tg,Ug);this.o=[{value:"Bug",desc:Ag},{value:"FeatureRequest",desc:Bg},{value:"MirroringQuality",desc:Cg},{value:"Discovery",desc:Dg},{value:"Other",desc:Eg}];this.g.feedbackTypes=this.o;this.g.includeFineLogs=!0;this.g.feedbackType="Bug";this.g.sendFeedback=
this.Hx.bind(this);this.g.cancel=this.ws.bind(this);this.g.attachLogsClick=this.m.bind(this);this.g.viewLogs=this.G.bind(this);this.g.$watchGroup("videoSmoothness videoQuality audioQuality feedbackDescription comments feedbackType".split(" "),this.zs.bind(this));this.g.sufficientFeedback=!1;this.g.$watch("attachLogs",this.m.bind(this));this.g.attachLogs=!0;this.u=Ce();this.g.userEmail="";chrome.identity.getProfileUserInfo(function(d){c.g.userEmail=d.email;Ai(c)});this.g.yourAnswerText=dh;this.g.language=
chrome.i18n&&chrome.i18n.getUILanguage?chrome.i18n.getUILanguage():chrome.runtime.getManifest().default_locale;this.g.requestLogsInProgress=!1;this.g.mrVersion=chrome.runtime.getManifest().version};k=Bi.prototype;k.vl=function(a){for(var b=[],c=1;c<arguments.length;c++)b.push(new Ci(c,arguments[c]));b.push(new Ci(0,arguments[0]));return b};k.ws=function(){this.g.feedbackDescription&&!confirm(Vg)||window.close()};
k.zs=function(){var a=this.g.feedbackType;this.g.sufficientFeedback="MirroringQuality"==a?this.g.videoSmoothness||this.g.videoQuality||this.g.audioQuality||this.g.comments:"Discovery"==a?this.g.visibleInSetup||this.g.comments:!!this.g.feedbackDescription};
k.Hx=function(){if(this.g.sufficientFeedback){var a=this.g.feedbackType,b="";"MirroringQuality"==a?(this.g.videoSmoothness&&(b+="\nVideo Smoothness: "+this.g.videoSmoothness),this.g.videoQuality&&(b+="\nVideo Quality: "+this.g.videoQuality),this.g.audioQuality&&(b+="\nAudio: "+this.g.audioQuality),this.g.projectedContentUrl&&(b+="\nProjected Content/URL: "+this.g.projectedContentUrl),this.g.comments&&(b+="\nComments: "+this.g.comments)):"Discovery"==a?(this.g.visibleInSetup&&(b+="\nChromecast Visible in Setup: "+
this.g.visibleInSetup),this.g.hasNetworkSoftware&&(b+="\nUsing VPN/proxy/firewall/NAS Software: "+this.g.hasNetworkSoftware),this.g.networkDescription&&(b+="\nNetwork Description: "+this.g.networkDescription),this.g.comments&&(b+="\nComments: "+this.g.comments)):b=this.g.feedbackDescription;a="Type: "+a+"\n\n"+b;this.g.sendDialogText=Wg;this.g.okButton=ch;this.g.feedbackSent=!1;this.D.show({locals:{iN:this.g.feedbackSent,KN:this.g.sendDialogText,Pv:this.g.okButton},scope:this.g,preserveScope:!0,bindToController:!0,
template:'<md-dialog id="feedback-confirmation"><md-dialog-content><div id="send-feedback-text">{{sendDialogText}}</div><md-dialog-actions><md-button class="md-raised md-primary"ng-disabled="!feedbackSent" ng-click="closeWindow()">{{okButton}}</md-button></md-dialog-actions></md-dialog-content></md-dialog>',controller:this.j});this.cp(a,Date.now())}};k.cp=function(a,b){var c=Date.now();!this.g.requestLogsInProgress||5E3<c-b?Di(this,a):setTimeout(this.cp.bind(this),1E3,a,b)};
var Di=function(a,b){var c=0,d=function(f,g,h){h?f(!0):(a.g.sendDialogText=Zg,Ai(a),g(Error("Failed to send")))},e=chrome.declarativeWebRequest?"MrTeamfood":"MRStable";(new sf(function(){c++;return new Promise(function(f,g){var h=a.g.userEmail,m=a.h;f=d.bind(null,f,g);g=chrome.runtime.getManifest();yg({productId:85561,bucket:e,flow:"submit",serverUri:"https://www.google.com/tools/feedback",allowNonLoggedInFeedback:!0,locale:g.default_locale,enableAnonymousFeedback:!h,report:{description:b},callback:f},
{version:g.version,description:g.description,user_email:h||"NA",logs:m.Kc||"NA",external_logs:m.g||"NA",device_model:m.modelName||"NA",receiver_version:m.u||"NA",dash_report_url:m.l||"NA",cast_device_counts:m.h,dial_device_counts:m.j,mirroring_service_enabled:m.m,native_cast_mrp_enabled:m.D,native_dial_mrp_enabled:m.o})})},1E4,4)).start().then(function(){zb("MediaRouter.Ui.Action.Feedback");a.g.sendDialogText=Yg;a.g.feedbackSent=!0;Ai(a)},function(){a.g.sendDialogText=Xg;a.g.feedbackSent=!0;Ai(a)})};
Bi.prototype.m=function(){var a=this;this.h=new zg;this.g.attachLogs&&(this.g.requestLogsInProgress=!0,chrome.runtime.sendMessage(new Df(this.u,"retrieve_log_data"),function(b){a.g.requestLogsInProgress=!1;a.h.Kc=b.logs||"no extension";a.h.Kc+="\n";a.h.Kc+=b.mediaSinkServiceStatus||"no media sink service status from browser";a.h.Kc+="\n";a.h.Kc+=b.mediaRouterLogs||"no Media Router logs from the browser";b.castStreamingLogs&&(a.h.l=b.castStreamingLogs);b.castDeviceCounts&&(a.h.h=b.castDeviceCounts);
b.dialDeviceCounts&&(a.h.j=b.dialDeviceCounts);a.h.m=!!b.mirroringServiceEnabled;a.h.D=!!b.nativeCastMrpEnabled;a.h.o=!!b.nativeDialMrpEnabled;if(b=b.device)if(b.model&&(a.h.modelName=b.model),b.version&&(a.h.u=b.version),!a.l){var c=Ce();a.l=!0;a.h.g=zf(b.ip,c,a.C.bind(a))}}))};
Bi.prototype.G=function(){this.g.logs=this.h.Kc;this.g.logsHeader=$g;this.g.sendLogs=ah;this.g.fineLogsWarning=bh;this.g.okButton=ch;this.D.show({locals:{XM:this.g.attachLogs,Kc:this.g.logs,oN:this.g.includeFineLogs,AN:this.g.logsHeader,LN:this.g.sendLogs,jN:this.g.fineLogsWarning,Pv:this.g.okButton},scope:this.g,preserveScope:!0,bindToController:!0,clickOutsideToClose:!0,template:'<md-dialog><md-dialog-content id="logs-dialog"><div class="subheading">{{logsHeader}}</div><div ng-show="includeFineLogs && attachLogs"id="feedback-fine-log-warning" class="informative">{{fineLogsWarning}}</div><pre>{{logs}}</pre><div class="send-logs"><md-checkbox type="checkbox" ng-model="attachLogs"ng-change="attachLogsClick()"><span>{{sendLogs}}</span></md-checkbox></div><md-dialog-actions><md-button class="md-raised md-primary"ng-click="closeDialog()">{{okButton}}</md-button></md-dialog-actions></md-dialog-content></md-dialog>',
controller:this.j})};Bi.prototype.C=function(a,b){this.l=!1;this.h.g="error"==a?"":b;this.g.attachLogs||(this.h.g="");Ai(this)};var Ai=function(a){a.g.$$phase||a.g.$apply()};Bi.prototype.j=function(a,b){a.closeWindow=function(){window.close()};a.closeDialog=function(){b.hide()}};Bi.prototype.j.$inject=["$scope","$mdDialog"];var Ci=function(a,b){this.id=a;this.desc=b;this.text=0==a?b:a+" ("+b+")"};
angular.module("feedbackApp","chrome_18n material.components.button material.components.checkbox material.components.dialog material.components.input material.components.radioButton".split(" ")).controller("FeedbackCtrl",["$scope","$mdDialog",Bi]);v("ng.safehtml.googSceHelper.isGoogHtmlType",function(a){return a&&a.vd?!0:!1});v("ng.safehtml.googSceHelper.isCOMPILED",function(){return!0});v("ng.safehtml.googSceHelper.unwrapAny",function(a){if(a instanceof hd)return id(a).toString();if(a instanceof ne)return oe(a).toString();if(a instanceof Ed)return Fd(a);if(a instanceof Md)return Nd(a);if(a instanceof $c)return ad(a).toString();throw Error();});
v("ng.safehtml.googSceHelper.unwrapGivenContext",function(a,b){if("html"==a)return oe(b).toString();if("resourceUrl"==a||"templateUrl"==a)return id(b).toString();if("url"==a)return b instanceof hd?id(b).toString():Fd(b);if("css"==a)return Nd(b);if("js"==a)return ad(b).toString();throw Error();});
