'use strict';var hy={TAB:0,Nl:1,br:2},iy=function(){return new pb("MediaRouter.CastStreaming.Session.Launch")},jy=function(){return new wb("MediaRouter.CastStreaming.Session.Length")},ky=function(a){Ab("MediaRouter.CastStreaming.Start.Success",a,hy)};var ly=eb("mr.mirror.cast.LogUploader"),ny=function(a,b,c){my("raw_events.log.gz",a,b,c);return b?"https://crash.corp.google.com/samples?reportid=&q="+encodeURIComponent("UserComments='"+b+"'"):""},my=function(a,b,c,d){if(0==b.size)ly.info("Trying to upload an empty file to Crash"),d&&d(null);else{var e=new FormData;e.append("prod","Cast");e.append("ver",chrome.runtime.getManifest().version);e.append(a,b);c&&e.append("comments",c);Wv("https://clients2.google.com/cr/report",function(f){f=f.target;
var g=null;fw(f)?(g=hw(f),ly.info("Upload to Crash succeeded: "+g)):ly.info("Upload to Crash failed. HTTP status: "+f.Ia());d&&d(g)},"POST",e,void 0,3E4)}};var oy=function(){this.g=0;nm(this)},qy=function(){py||(py=new oy);return py},ry=function(){var a=qy(),b={fraction:.01,autoSubmitTimeLimitMillis:6048E5},c=b.autoSubmitTimeLimitMillis,d=Date.now();return a.g&&c&&d-a.g<c?!1:Math.random()<b.fraction};oy.prototype.Va=function(){return"mirror.cast.LogUtils"};oy.prototype.Kb=function(){return[void 0,{lastAutoSubmitMillis:this.g}]};oy.prototype.Jb=function(){var a=lm(this);this.g=a&&a.lastAutoSubmitMillis||0};var py=null;eb("mr.mirror.cast.LogUtils");var sy={OG:"OFFER",hz:"ANSWER",EH:"PRESENTATION",iD:"GET_STATUS",vK:"STATUS_RESPONSE",dD:"GET_CAPABILITIES",IA:"CAPABILITIES_RESPONSE",yJ:"RPC"};var ty=function(){this.capabilities=this.status=this.g=this.error=this.rpc=this.result=this.type=this.h=this.sessionId=null},wy=function(a){try{if("string"!==typeof a)throw SyntaxError("Cannot parse non-string as JSON");var b;uy(JSON.parse(a),function(d){b=vy(d)},function(){throw Error("non-Object result from JSON parse");});return b}catch(d){var c=d instanceof SyntaxError?"JSON parse error: "+d.message:"Type coercion error: "+d.message}"string"==typeof a?a="a string: "+a:a instanceof ArrayBuffer?
(a=new Uint8Array(a),a="an ArrayBuffer whose base64 is "+btoa(String.fromCharCode.apply(null,a))):a="of invalid data type "+typeof a;throw Error(c+". Input was "+a);},vy=function(a){var b=new ty;null!=a.sessionId&&(b.sessionId=String(a.sessionId));xy(a.seqNum,function(f){b.h=f},function(){throw Error('"seqNum" must be a number');});if("type"in a){for(var c=String(a.type).toUpperCase(),d=n(Object.keys(sy)),e=d.next();!e.done;e=d.next())if(sy[e.value]==c){b.type=c;break}if(!b.type)throw Error('not a known message "type"');
}"result"in a&&(b.result=String(a.result));if("rpc"in a){if("string"!==typeof a.rpc)throw Error('"rpc" must be a String containing a base64 payload');b.rpc=new Uint8Array([].concat(p(atob(a.rpc))).map(function(f){return f.charCodeAt(0)}))}uy(a.error,function(f){b.error=yy(f)},function(){throw Error('"error" must be an Object');});uy(a.answer,function(f){b.g=zy(f)},function(){throw Error('"answer" must be an Object');});uy(a.status,function(f){b.status=Ay(f)},function(){throw Error('"status" must be an Object');
});uy(a.capabilities,function(f){b.capabilities=By(f)},function(){throw Error('"capabilities" must be an Object');});return b},uy=function(a,b,c){void 0!==a&&(a instanceof Object?b(a):c())},xy=function(a,b,c){void 0!==a&&("number"!==typeof a?c():b(a))},Cy=function(a,b,c){void 0!==a&&(a instanceof Array&&a.every(function(d){return"number"===typeof d})?b(a):c())},Dy=function(a,b,c){void 0!==a&&(a instanceof Array?b(a.map(function(d){return String(d)})):c())},Ey=function(){this.m=null;this.g=[];this.h=
[];this.j=this.l=this.D=null},zy=function(a){var b=new Ey;xy(a.udpPort,function(c){b.m=c},function(){throw Error('"answer.udpPort" must be a number');});Cy(a.sendIndexes,function(c){b.g=c},function(){throw Error('"answer.sendIndexes" must be an array of numbers');});Cy(a.ssrcs,function(c){b.h=c},function(){throw Error('"answer.ssrcs" must be an array of numbers');});"IV"in a&&(b.D=String(a.IV));"receiverGetStatus"in a&&(b.l="true"==String(a.receiverGetStatus).toLowerCase());"castMode"in a&&(b.j=String(a.castMode));
return b},Fy=function(){this.details=this.description=this.code=null},yy=function(a){var b=new Fy;xy(a.code,function(c){b.code=c},function(){throw Error('"error.code" must be a number');});"description"in a&&(b.description=String(a.description));uy(a.details,function(c){b.details=c},function(){throw Error('"error.details" must be an Object');});return b},Gy=function(){this.h=this.g=null},Ay=function(a){var b=new Gy;xy(a.wifiSnr,function(c){b.g=c},function(){throw Error('"status.wifiSnr" must be a number');
});Cy(a.wifiSpeed,function(c){b.h=c},function(){throw Error('"status.wifiSpeed" must be an array of numbers');});return b},Hy=function(){this.h=this.g=null},By=function(a){var b=new Hy;Dy(a.mediaCaps,function(c){b.g=c},function(){throw Error('"capabilities.mediaCaps" must be an array');});if("keySystems"in a){a=a.keySystems;if(!(a instanceof Array))throw Error('"capabilities.keySystems" must be an array');b.h=a.map(function(c){var d;uy(c,function(e){d=Iy(e)},function(){throw Error('"capabilities.keySystems" entries must be *Objects');
});return d})}return b},Jy=function(){this.h=this.D=this.m=this.l=this.u=this.g=this.o=this.codecs=this.initDataTypes=this.j=null},Iy=function(a){var b=new Jy;"keySystemName"in a&&(b.j=String(a.keySystemName));Dy(a.initDataTypes,function(c){b.initDataTypes=c},function(){throw Error('"capabilities.initDataTypes" must be an array');});Dy(a.codecs,function(c){b.codecs=c},function(){throw Error('"capabilities.codecs" must be an array');});Dy(a.secureCodecs,function(c){b.o=c},function(){throw Error('"capabilities.secureCodecs" must be an array');
});Dy(a.audioRobustness,function(c){b.g=c},function(){throw Error('"capabilities.audioRobustness" must be an array');});Dy(a.videoRobustness,function(c){b.u=c},function(){throw Error('"capabilities.videoRobustness" must be an array');});"persistentLicenseSessionSupport"in a&&(b.l=String(a.persistentLicenseSessionSupport));"persistentReleaseMessageSessionSupport"in a&&(b.m=String(a.persistentReleaseMessageSessionSupport));"persistentStateSupport"in a&&(b.D=String(a.persistentStateSupport));"distinctiveIdentifierSupport"in
a&&(b.h=String(a.distinctiveIdentifierSupport));return b};var Ky=function(a){this.s=eb("mr.mirror.cast.MessageDispatcher");this.l=a;this.g=null;this.h=new Map;this.j=0},Ly=function(a,b,c){if(a.h.has(b))throw Error("Attempt to multiple-subscribe to the same response type: "+b);a.h.set(b,c);a.j=0;lb(a.s,"Added subscriber for "+b+"-type messages.");a.g||(a.g=cx(a.l),a.g.onMessage=a.m.bind(a))},My=function(a,b){a.h.delete(b)&&lb(a.s,function(){return"Removed subscriber of "+b+"-type messages."});0==a.h.size&&a.g&&(a.g.dispose(),a.g=null)};
Ky.prototype.sendMessage=function(a){return this.g?"RPC"==a.type?this.g.sendMessage(a,{namespace:"urn:x-cast:com.google.cast.remoting"}):this.g.sendMessage(a,{namespace:"urn:x-cast:com.google.cast.webrtc"}):Promise.reject(Error("Require at least one subscriber before sending messages."))};
var Ny=function(a,b,c,d,e){var f=null,g=function(){My(a,c);null!=f&&(clearTimeout(f),f=null)};try{Ly(a,c,function(h){e(h)&&g()})}catch(h){e(null,h);return}f=setTimeout(function(){g();e(null,Error("timeout"))},d);a.sendMessage(b).catch(function(h){g();e(null,h)})};
Ky.prototype.m=function(a){if(a&&"string"===typeof a.namespace_&&a.namespace_.startsWith("urn:x-cast:com.google.cast.")){do{var b=void 0;try{b=wy(a.data)}catch(d){b=d.message;break}if(b.type){var c=this.h.get(b.type);if(c)try{c(b);return}catch(d){b="Error thrown during delivery. Response was: "+(JSON.stringify(b)+". Error from subscriber callback was: ")+(d.message+".")}else b="Message was ignored: "+JSON.stringify(b)}else b="Message did not include response type: "+JSON.stringify(b)}while(0);10>
this.j?this.s.K(b):lb(this.s,b);++this.j}};var Oy=function(){this.g=Promise.resolve(1)},Qy=function(a,b,c){return Py(a,function(d){return d==b},c)},Ry=function(a,b){var c=[3,4];return Py(a,function(d){return-1!=c.indexOf(d)},b)},Sy=function(a,b){a.g=a.g.catch(function(){return 1});return Py(a,function(){return!0},b)},Py=function(a,b,c){var d,e,f=new Promise(function(g,h){d=g;e=h});a.g=a.g.then(function(g){if(!b(g))return e(Error("Operation requires a different starting checkpoint than "+g)),Promise.resolve(g);var h=new Ty(g);try{var m=c(h)}catch(q){m=
Promise.reject(q)}return m.then(function(q){return d(q)},function(q){return e(q)}).then(function(){if(null===h.g)throw Error("A prior operation that started at "+(g+" did not complete."));return h.g})},function(g){e(g);throw g;});return f},Ty=function(a){this.h=a;this.g=null},Uy=function(a,b){a.g="number"===typeof b?b:a.h};var Vy=chrome.cast.streaming,Wy=eb("mr.mirror.cast.StreamingLaunchWorkflow"),Yy=function(a,b,c,d,e){this.X=a.sessionId;this.C=a.mh;this.R=a.ze;this.j=b;this.M=c;this.J=d;this.W=Xy(e,"onAnswer",this.C);this.aa=Xy(e,"onSessionStop",this.C);this.s=Wy;this.G=new Oy;this.o=this.F=this.u=this.h=this.g=this.D=this.m=this.l=null};
Yy.prototype.start=function(a,b,c){var d=this;if(!a&&!b)return Promise.reject(Error("No tracks to stream"));var e=a instanceof Zy,f=b instanceof Zy;(e&&b&&!f||f&&a&&!e)&&Mb("Mixing remoting and non-remoting tracks");return Qy(this.G,1,function(g){d.l=a;d.m=b;d.D=c;d.s.info(function(){return"Launching streaming for "+$y(d)+" to a "+(d.R+".")});return az(d).then(d.H.bind(d)).then(function(h){return bz(d,h).then(function(m){d.W();var q=cz(d,m,h);d.g=dz(d,d.g,q);d.h=dz(d,d.h,q);if(!d.g&&!d.h)throw Error("Receiver did not select any offers from: "+
JSON.stringify(h));d.F=!!m.l;d.o=function(r,y){r==d.g?d.D.jf("Audio stream (id="+r+") error: "+y):r==d.h&&d.D.jf("Video stream (id="+r+") error: "+y)};Vy.rtpStream.onError.addListener(d.o);return ez(d,m,q)})}).then(function(){d.s.info(function(){return"Launched streaming for "+$y(d)});d.D.Bg(d);Uy(g,2);return{hs:d.g,Fy:d.h}})})};
Yy.prototype.stop=function(){var a=this;return Sy(this.G,function(b){if(!a.l&&!a.m)return Uy(b,1),Promise.resolve();a.s.info(function(){return"Stopping streaming for "+$y(a)+"."});a.o&&(Vy.rtpStream.onError.removeListener(a.o),a.o=null);if(a.D){var c=a.D.rh();a.D=null}else c=Promise.resolve();return c.then(function(){a.g&&(Vy.rtpStream.stop(a.g),Vy.rtpStream.destroy(a.g),a.g=null);a.h&&(Vy.rtpStream.stop(a.h),Vy.rtpStream.destroy(a.h),a.h=null);a.u&&(Vy.udpTransport.destroy(a.u),a.u=null);a.aa();
a.s.info(function(){return"Stopped streaming for "+$y(a)+"."});a.l=null;a.m=null;Uy(b,1)})})};
var fz=function(a,b){var c=JSON.stringify(b);return Promise.all([a.g&&new Promise(function(d){return Vy.rtpStream.getRawEvents(a.g,c,d)}),a.h&&new Promise(function(d){return Vy.rtpStream.getRawEvents(a.h,c,d)})]).catch(function(d){a.s.error("Unexpected error when calling getRawEvents()",d);return[]}).then(function(d){return new Blob(d.filter(function(e){return!!e}),{type:"application/gzip"})})},gz=function(a){return Promise.all([a.g&&new Promise(function(b){return Vy.rtpStream.getStats(a.g,b)}),a.h&&
new Promise(function(b){return Vy.rtpStream.getStats(a.h,b)})]).catch(function(b){a.s.error("Unexpected error when calling getStats()",b);return[]}).then(function(b){return Object.assign.apply(Object,[{}].concat(p(b.filter(function(c){return!!c}))))})},$y=function(a){if(a.l&&a.m)var b="audio+video ";else if(a.l)b="audio-only ";else if(a.m)b="video-only ";else return"stopped";return a.l instanceof Zy||a.m instanceof Zy?b+"remoting":b+"streaming"},az=function(a){return new Promise(function(b){var c=
function(d,e,f){d&&!a.l&&(Vy.rtpStream.destroy(d),d=null);e&&!a.m&&(Vy.rtpStream.destroy(e),e=null);a.s.info(function(){return"Created Cast Streaming session: audioStreamId="+d+", videoStreamId="+e+"."});a.g=d;a.h=e;a.u=f;b()};a.l instanceof Zy||a.m instanceof Zy?Vy.session.create(null,null,c):Vy.session.create(a.l,a.m,c)})};
Yy.prototype.H=function(){for(var a=kk(),b=kk(),c=[],d=n([this.g,this.h]),e=d.next();!e.done;e=d.next())if(e=e.value)for(var f=e==this.g,g=f?127:96,h=f?Math.floor(499999*Math.random())+1:Math.floor(499999*Math.random())+500001,m=f?48E3:9E4,q=n(Vy.rtpStream.getSupportedParams(e)),r=q.next();!r.done;r=q.next())r=r.value,r.payload.payloadType=g,r.payload.maxLatency=this.j.maxLatencyMillis,r.payload.minLatency=this.j.minLatencyMillis,r.payload.animatedLatency=this.j.animatedLatencyMillis,r.payload.ssrc=
h,r.payload.clockRate=m,r.payload.aesKey=a,r.payload.aesIvMask=b,f?(r.payload.channels=2,r.payload.maxBitrate=this.j.audioBitrate,r.payload.maxFrameRate=100):(r.payload.minBitrate=this.j.minVideoBitrate,r.payload.maxBitrate=this.j.maxVideoBitrate,r.payload.maxFrameRate=this.j.maxFrameRate),c.push(new hz(e,r));return c};
var dz=function(a,b,c){b&&!c.some(function(d){return d.eg==b})&&(a.s.K("Destroying RTP stream not selected by the receiver: id="+b),Vy.rtpStream.destroy(b),b=null);return b},bz=function(a,b){return new Promise(function(c,d){for(var e=[],f=0;f<b.length;++f){var g=b[f].params,h={index:f,codecName:g.payload.codecName.toLowerCase(),rtpProfile:"cast",rtpPayloadType:g.payload.payloadType,ssrc:g.payload.ssrc,targetDelay:g.payload.animatedLatency,aesKey:g.payload.aesKey,aesIvMask:g.payload.aesIvMask,timeBase:"1/"+
g.payload.clockRate,receiverRtcpEventLog:a.j.enableLogging,rtpExtensions:["adaptive_playout_delay"]};a.j.dscpEnabled&&(h.receiverRtcpDscp=46);127==g.payload.payloadType?Object.assign(h,{type:"audio_source",bitRate:0<g.payload.maxBitrate?1E3*g.payload.maxBitrate:60*g.payload.maxFrameRate+g.payload.clockRate*g.payload.channels,sampleRate:g.payload.clockRate,channels:g.payload.channels}):Object.assign(h,{type:"video_source",renderMode:"video",maxFrameRate:Math.round(1E3*g.payload.maxFrameRate)+"/1000",
maxBitRate:1E3*g.payload.maxBitrate,resolutions:[{width:a.j.maxWidth,height:a.j.maxHeight}]});e.push(h)}var m=a.l instanceof Zy||a.m instanceof Zy?"remoting":"mirroring",q={type:"OFFER",sessionId:a.X,seqNum:yn(a.M),offer:{castMode:m,receiverGetStatus:!0,supportedStreams:e}};a.s.info(function(){return"Sending OFFER message: "+JSON.stringify(q)});Ny(a.J,q,"ANSWER",1E4,function(r,y){if(null==r)d(y);else if("ok"==r.result&&r.g){if(r.h!=q.seqNum)return a.s.K("Ignoring ANSWER for OFFER with different seqNum: "+
JSON.stringify(r)),!1;((y=r.g.j)&&y!=m||!y&&"mirroring"!=m)&&a.s.error("Expected receiver to ANSWER with castMode="+m+", but got: "+y);lb(a.s,function(){return"Received ANSWER: "+JSON.stringify(r)});c(r.g)}else d(Error("Non-OK ANSWER received: "+JSON.stringify(r)));return!0})})},cz=function(a,b,c){if(b.g.length!=b.h.length)return a.s.error("sendIndexes.length != ssrcs.length in ANSWER: "+JSON.stringify(b)),[];for(var d=[],e={},f=0;f<b.g.length;e={wf:e.wf},++f){var g=b.g[f];if(0>g||g>=c.length)return a.s.error("Receiver selected invalid index ("+
g+" < "+c.length+") in ANSWER: "+JSON.stringify(b)),[];e.wf=c[g];if(d.some(function(h){return function(m){return m.eg==h.wf.eg}}(e)))return a.s.error("Receiver selected same RTP stream twice in ANSWER: "+JSON.stringify(b)),[];e.wf.params.payload.feedbackSsrc=b.h[g];if(d.some(function(h){return function(m){return m.params.payload.feedbackSsrc==h.wf.params.payload.feedbackSsrc}}(e)))return a.s.error("Receiver provided same SSRC for two different RTP streams in ANSWER: "+JSON.stringify(b)),[];d.push(e.wf)}return d},
ez=function(a,b,c){var d=null,e=function(){d&&(Vy.rtpStream.onStarted.removeListener(d),d=null)};return(new Promise(function(f,g){var h=b.m||2344;a.s.info(function(){return"Starting RTP streams to receiver at "+(a.C+":"+h)+(" for selected offers: "+JSON.stringify(c))});var m=a.u||-1;a.j.dscpEnabled&&(a.s.info("Enabled DSCP in sender."),Vy.udpTransport.setOptions(m,{DSCP:!0}));Vy.udpTransport.setDestination(m,{address:a.C,port:h});var q=new Set(c.map(function(y){return y.eg}));d=function(y){q.delete(y);
0==q.size&&f()};Vy.rtpStream.onStarted.addListener(d);m=n(c);for(var r=m.next();!r.done;r=m.next())r=r.value,Vy.rtpStream.toggleLogging(r.eg,a.j.enableLogging),Vy.rtpStream.start(r.eg,r.params);setTimeout(function(){g(Error("Timeout: RTP streams failed to start."))},1E4)})).then(e).catch(function(f){e();throw f;})},Xy=function(a,b,c){return a&&b in a?function(){try{a[b](c)}catch(d){Wy.error("Error from testHooks."+b,d)}}:function(){}},hz=function(a,b){this.eg=a;this.params=b},Zy=function(){};var iz=eb("mr.mirror.cast.MediaRemoter"),lz=function(a,b,c,d,e,f){this.o=a;this.J=jz(b,this.o.tb);this.M=new Yy(this.o.tb,c,d,e,f);this.F=e;this.m=new Oy;this.j=new kz;this.G=new mojo.Binding(mojo.MirrorServiceRemoter,this,null);this.s=iz;this.C=this.g=this.D=this.l=this.H=null;this.h=!0;this.u=this.X.bind(this)},oz=function(a,b,c){return Qy(a.m,1,function(d){a.H=b;a.l=c;var e=a.G.createInterfacePtrAndBind();a.G.setConnectionErrorHandler(function(){a.s.info("Remoter mojo pipe connection error.");
mz(a)});a.g=new mojo.MirrorServiceRemotingSourcePtr;var f=Aj(a.o.mediaSource||"");if(!f)throw Error("Failed to parse tab ID from source:\n          "+a.o.mediaSource);a.s.info("Connecting remoter to browser: tabId="+f);(jj.get("mr.ProviderManager")||null).onMediaRemoterCreated(f,e,mojo.makeRequest(a.g));a.g.ptr.setConnectionErrorHandler(function(){a.s.info("RemotingSource mojo pipe connection error.");mz(a)});return nz(a).then(function(){if(a.h)a.g.onSinkAvailable(a.J);Uy(d,2)})})},mz=function(a){return Sy(a.m,
function(b){a.g&&(a.g.ptr.reset(),a.g=null);var c=a.D;a.D=null;a.l=null;a.H=null;a.G.close();chrome.settingsPrivate.onPrefsChanged.hasListener(a.u)&&chrome.settingsPrivate.onPrefsChanged.removeListener(a.u);return new Promise(function(d){window.setTimeout(function(){pz(a).then(function(){Uy(b,1);d();c&&c()})},250)})})};k=lz.prototype;k.Ix=function(a){qz(this.j,a)};k.Bg=function(a){this.l&&this.l.Bg(a)};k.rh=function(){return this.l?this.l.rh():Promise.resolve()};
k.jf=function(a,b){this.s.error("Error during streaming: "+a,b);if(this.g)this.g.onError();mz(this)};
k.start=function(){var a=this,b=!1;this.s.info(function(){b=!0;return"Starting next media remoting session."});b&&rz(this.j,function(c){return a.s.info(c)});sz(this.j);Qy(this.m,2,function(c){return(0,a.H)().then(function(d){a.D=d;Ly(a.F,"RPC",function(e){if(e.rpc){var f=a.j;e=e.rpc;f.D&&(++f.o,f.h+=e.length,f.D(e))}});Uy(c,3)}).catch(function(d){return pz(a).then(function(){Uy(c);throw d;})})}).then(function(){a.s.info("Remoting started successfully.")}).catch(function(c){a.s.error("Failed to start remoting",c);
a.g.onError()})};k.ly=function(a,b){var c=this;return Qy(this.m,3,function(d){return c.M.start(a?new Zy:null,b?new Zy:null,c).then(function(e){tz(c.j,function(f){return c.F.sendMessage(f)},function(f){c.g.onMessageFromSink(f)});Uy(d,4);return{audio_stream_id:e.hs||-1,video_stream_id:e.Fy||-1}}).catch(function(e){return pz(c).then(function(){Uy(d);throw e;})})}).catch(function(d){c.s.error("Failed to start remoting streams",d);mz(c);return{audio_stream_id:-1,video_stream_id:-1}})};
k.stop=function(a){var b=this;Ry(this.m,function(c){b.g.onStopped(a);return pz(b).then(function(){b.s.info("Remoting stopped.");Uy(c,5);(0,b.D)().then(function(){return Qy(b.m,5,function(d){if(b.g&&b.h)b.g.onSinkAvailable(b.J);Uy(d,2);return Promise.resolve()})}).catch(function(d){throw d;});b.D=null})}).catch(function(c){b.s.error("Failed to stop remoting: ",c);mz(b)})};
k.Ls=function(){null===this.C&&(this.C=Cf(this.o.tb.mh).then(function(a){return a.h||!1}));return this.C.then(function(a){return{rate:(a?1E7:5E6)/8}})};
var pz=function(a){return a.M.stop().then(function(){My(a.F,"RPC");uz(a.j);vz(a.j)})},nz=function(a){return new Promise(function(b){chrome.settingsPrivate.getPref("media_router.media_remoting.enabled",function(c){chrome.runtime.lastError?a.s.error("Encountered error getting media remoting pref: "+JSON.stringify(chrome.runtime.lastError)):c.type!=chrome.settingsPrivate.PrefType.BOOLEAN?a.s.error("Pref value not a boolean: "+JSON.stringify(c)):(a.h=!!c.value,a.s.info("Initializing mediaRemotingEnabled_ with value read from pref: "+
a.h));chrome.settingsPrivate.onPrefsChanged.hasListener(a.u)||chrome.settingsPrivate.onPrefsChanged.addListener(a.u);b()})})};
lz.prototype.X=function(a){if(this.g){a=n(a);for(var b=a.next();!b.done;b=a.next())if(b=b.value,"media_router.media_remoting.enabled"==b.key){if(b.type!=chrome.settingsPrivate.PrefType.BOOLEAN){this.s.error("Pref value not a boolean: "+JSON.stringify(b));break}a=!!b.value;if(this.h==a)break;this.h=a;this.s.info("mediaRemotingEnabled_ changed to: "+this.h);if(this.h)this.g.onSinkAvailable(this.J);else this.g.onStopped(mojo.RemotingStopReason.USER_DISABLED);break}}};
var jz=function(a,b){var c=new mojo.RemotingSinkMetadata;c.features=[];c.friendly_name=b.hy||"";c.audio_capabilities=[];c.video_capabilities=[];var d=mojo.RemotingSinkAudioCapability,e=mojo.RemotingSinkVideoCapability,f=c.audio_capabilities,g=c.video_capabilities,h=b.ze||"";(a.g||[]).forEach(function(m){switch(m){case "audio":f.push(d.CODEC_BASELINE_SET);break;case "aac":f.push(d.CODEC_AAC);break;case "opus":f.push(d.CODEC_OPUS);break;case "video":g.push(e.CODEC_BASELINE_SET);break;case "4k":g.push(e.SUPPORT_4K);
break;case "h264":g.push(e.CODEC_H264);break;case "vp8":g.push(e.CODEC_VP8);break;case "vp9":h.startsWith("Chromecast Ultra")&&g.push(e.CODEC_VP9);break;case "hevc":h.startsWith("Chromecast Ultra")&&g.push(e.CODEC_HEVC);break;default:iz.info("Unknown mediaCap name: "+m)}});b.ze&&"Chromecast Ultra"==b.ze&&g.push(e.SUPPORT_4K);return c};lz.prototype.estimateTransmissionCapacity=lz.prototype.Ls;lz.prototype.stop=lz.prototype.stop;lz.prototype.startDataStreams=lz.prototype.ly;lz.prototype.start=lz.prototype.start;
lz.prototype.sendMessageToSink=lz.prototype.Ix;
var kz=function(){this.D=this.m=this.g=null;this.C=this.h=this.o=this.j=this.u=0;this.l=null},sz=function(a){a.g=[];wz(a,performance.now())},tz=function(a,b,c){a.m=b;a.D=c;a.g?(b=a.g,a.g=null,b.forEach(function(d){return qz(a,d.data).then(d.Kx,d.ep)})):wz(a,performance.now())},uz=function(a){if(a.g){var b=Error("Stop before delivering pending message");a.g.forEach(function(c){return c.ep(b)});a.g=null}a.m=null;a.D=null},qz=function(a,b){if(a.m){var c=btoa(String.fromCharCode.apply(null,b));++a.u;
a.j+=b.length;return a.m({type:"RPC",rpc:c})}return a.g?new Promise(function(d,e){a.g.push({data:b,Kx:d,ep:e})}):Promise.reject(Error("RPC pipe not started"))},rz=function(a,b){vz(a);a.l=setInterval(function(){if(a.g)var c=a.g.length+" messages are waiting to send.";else{c=performance.now();var d=(c-a.C)/1E3;d="Over the past "+d.toFixed(1)+" seconds, sent "+(a.u+" messages ("+Math.round(a.j/d)+" bytes/sec) and received ")+(a.o+" messages ("+Math.round(a.h/d)+" bytes/sec).");wz(a,c);c=d}b(c)},3E4)},
vz=function(a){null!=a.l&&(clearInterval(a.l),a.l=null)},wz=function(a,b){a.u=0;a.j=0;a.o=0;a.h=0;a.C=b};var xz=function(a){return a&&a.getAudioTracks()&&0<a.getAudioTracks().length?a.getAudioTracks()[0]:null},yz=function(a){return a&&a.getVideoTracks()&&0<a.getVideoTracks().length?a.getVideoTracks()[0]:null};var zz=function(a,b,c,d,e){this.j=new Yy(a,b,c,d,void 0===e?null:e);this.s=eb("mr.mirror.cast.MediaStreamer");this.m=new Oy;this.l=this.h=this.g=this.D=null};zz.prototype.start=function(a,b){var c=this;return Qy(this.m,1,function(d){c.D=a;c.g=xz(a);c.g&&"ended"==c.g.readyState&&(c.g=null);c.h=yz(a);c.h&&"ended"==c.h.readyState&&(c.h=null);if(!c.g&&!c.h)return Uy(d),Promise.reject(Error("No MediaStream tracks to stream."));c.l=b;return c.j.start(c.g,c.h,c.l).then(function(){return Uy(d,2)})})};
zz.prototype.stop=function(){var a=this;return Sy(this.m,function(b){return a.j.stop().then(function(){a.g=null;a.h=null;a.D=null;a.l=null;Uy(b,1)})})};var Az=function(a){return Qy(a.m,2,function(b){a.s.info("Suspending media streaming...");return a.j.stop().then(function(){a.s.info("Suspended media streaming.");Uy(b,3)})})};
zz.prototype.resume=function(){var a=this;return Qy(this.m,3,function(b){a.g&&"ended"==a.g.readyState&&(a.g=null);a.h&&"ended"==a.h.readyState&&(a.h=null);if(!a.g&&!a.h)return Promise.reject(Error("Cannot resume: All tracks have ended."));a.s.info("Resuming media streaming...");return a.j.start(a.g,a.h,a.l).then(function(){a.s.info("Resumed media streaming.");Uy(b,2)})})};var Bz=function(a,b,c){this.m=a;this.l=b;this.j=c;this.s=eb("mr.mirror.cast.WifiStatusMonitor");this.g=null;this.h=[]};Bz.prototype.start=function(){var a=this;null==this.g&&(lb(this.s,"Starting Wifi Status Monitoring."),this.h=[],Ly(this.j,"STATUS_RESPONSE",function(b){return Cz(a,b)}),this.g=setInterval(function(){return Dz(a)},12E4),Dz(this))};Bz.prototype.stop=function(){null!=this.g&&(lb(this.s,"Stopping Wifi Status Monitoring."),clearInterval(this.g),this.g=null,My(this.j,"STATUS_RESPONSE"))};
var Cz=function(a,b){if(null!=a.g)if(b.status){var c={};null!=b.status.g&&(c.wifiSnr=b.status.g);null!=b.status.h&&(c.wifiSpeed=b.status.h[3]);0==Object.keys(c).length?a.s.K(function(){return"No status fields populated in response: "+JSON.stringify(b)}):(c.timestamp=Date.now(),30==a.h.length&&a.h.shift(),a.h.push(c),a.s.info(function(){return"Current Wifi status: "+JSON.stringify(c)}))}else a.s.K(function(){return"Ignoring response without status: "+JSON.stringify(b)})},Dz=function(a){a.j.sendMessage({type:"GET_STATUS",
sessionId:a.m,seqNum:yn(a.l),get_status:["wifiSnr","wifiSpeed"]})};var Ez=function(a,b,c,d){this.H=b.mh;this.J={extVersion:chrome.runtime.getManifest().version,extChannel:"public",mirrorSettings:Qj(a),sender:navigator.userAgent||"UNKNOWN",receiverProductName:b.ze};this.F=c;this.G=d;this.l=this.h=this.o=this.D=this.m=this.u=this.j=null;this.g=[]};Ez.prototype.Bg=function(a){null!=this.h&&clearInterval(this.h);this.j=a;this.u=Date.now();this.h=setInterval(this.C.bind(this,a),9E5)};
Ez.prototype.rh=function(){null!=this.h&&(clearInterval(this.h),this.h=null);if(null!=this.j){var a=this.C(this.j);this.j=null;return a}return Promise.resolve()};Ez.prototype.jf=function(a,b){null==this.m&&(this.m=Date.now(),"function"===typeof a?this.D=a():"string"===typeof a&&(this.D=a),b&&"string"===typeof b.stack&&(this.o=b.stack))};
var Gz=function(a,b){return(null==a.j?Promise.resolve():a.C(a.j)).then(function(){var c=b.map(function(d){d=Fz(a,d);var e=d.map(function(g){return g.events}).filter(function(g){return null!=g}),f=["["];d.map(function(g){return g.dg}).forEach(function(g,h){0<h&&f.push(",");f.push(g)});f.push("]");return{events:new Blob(e,{type:"application/gzip"}),dg:new Blob(f,{type:"application/json"})}});a.g=[];return c})};
Ez.prototype.C=function(a){var b=this;if(null!=this.l)return this.l;var c=Cf(this.H).then(function(d){d={receiverVersion:d.g,receiverConnected:d.l,receiverOnEthernet:d.h,receiverHasUpdatePending:d.j,receiverUptimeSeconds:d.m};Object.assign(d,b.J);var e=Date.now();Object.assign(d,{startTime:b.u,endTime:e,activity:$y(a),receiverWifiStatus:Array.from(b.G.h)});b.u=e;null!=b.m&&(Object.assign(d,{streamingErrorTime:b.m,streamingErrorMessage:b.D,streamingErrorCause:b.o}),b.m=null,b.D=null,b.o=null);return d});
return(this.l=Promise.all([c.then(function(d){return fz(a,d)}),c,gz(a)]).then(function(d){var e=n(d);d=e.next().value;var f=e.next().value;e=e.next().value;b.g.push({events:d,dg:new Blob([JSON.stringify(Object.assign({tags:f},e))],{type:"application/json"})});b.g=Fz(b,b.F);b.l=null}))||Promise.resolve()};
var Fz=function(a,b){b-=2;for(var c=[],d=a.g.length-1;0<=d;--d){b-=a.g[d].dg.size+1;if(0>b)break;c.push({events:null,dg:a.g[d].dg});if(null!=a.g[d].events){var e=a.g[d].events.size;b>=e&&(c[c.length-1].events=a.g[d].events,b-=e)}}return c.reverse()};var Hz=function(a,b,c,d){d=void 0===d?null:d;Nj.call(this,b);var e=b.tb;this.C=e.sessionId;this.H=a;this.M=d;this.s=eb("mr.mirror.cast.Session");this.u=new Oy;this.o=new xn("mirror.cast.SeqNumGenerator");this.D=new Ky(b.id);this.m=new zz(e,this.H,this.o,this.D,this.M);this.l=null;this.g=new Ez(a,e,c,new Bz(this.C,this.o,this.D));this.G=null};t(Hz,Nj);k=Hz.prototype;
k.start=function(a){var b=this;return Qy(this.u,1,function(c){var d=iy();return b.m.start(a,b).then(function(){b.m.j.F&&(b.g.G.start(),Iz(b));d.end();b.G=jy();Uy(c,2);return b})})};k.stop=function(){var a=this;return Sy(this.u,function(b){a.G&&(a.G.end(),a.G=null);a.g.G.stop();return a.m.stop().then(function(){return a.l?mz(a.l):Promise.resolve()}).then(function(){a.l=null;Uy(b,4)})})};
k.bp=function(){var a=this,b={sessionId:this.C,seqNum:yn(this.o),type:"PRESENTATION",icons:[],title:Lj(this.Dc)};this.s.info("Sending session metadata update to receiver: "+this.C);this.D.sendMessage(b).catch(function(c){a.s.K("Failed to send activity to sink: "+c.message)})};k.Bg=function(a){this.g.Bg(a)};k.rh=function(){return this.g.rh()};k.jf=function(a,b){this.g.jf(a,b);this.s.error(a,b);this.stop()};
var Jz=function(a,b){return Gz(a.g,b)},Iz=function(a){Kz(a).then(function(b){(b.g||[]).includes("video")?Lz(a,b):a.s.K(function(){return"Receiver incapable of Media Remoting: "+JSON.stringify(b)})}).catch(function(b){a.s.K("None/Invalid capabilites response. Media Remoting disabled.",b)})},Kz=function(a){return new Promise(function(b,c){var d={type:"GET_CAPABILITIES",sessionId:a.C,seqNum:yn(a.o)};a.s.info(function(){return"Sending GET_CAPABILITIES message: "+JSON.stringify(d)});Ny(a.D,d,"CAPABILITIES_RESPONSE",
3E4,function(e,f){if(null==e)return c(f),!0;if("ok"!=e.result||!e.capabilities)return c(Error("Bad response: "+JSON.stringify(e))),!0;if(e.h!=d.seqNum)return a.s.info(function(){return"Ignoring CAPABILITIES_RESPONSE with different seqNum: "+JSON.stringify(e)}),!1;lb(a.s,function(){return"Received CAPABILITIES_RESPONSE: "+JSON.stringify(e)});b(e.capabilities);return!0})})},Lz=function(a,b){Qy(a.u,2,function(c){var d=a.h.tb.ze||"<UNKNOWN>";if(!d.startsWith("Chromecast")&&!d.startsWith("Eureka Dongle"))return a.s.K('HACK: Media Remoting disabled because the receiver model--"'+
(d+'" according to discovery--is not a Chromecast.')),Uy(c),Promise.resolve();a.l=new lz(a.h,b,a.H,a.o,a.D,a.M);return oz(a.l,a.X.bind(a),a).catch(function(e){a.s.error("Media Remoting start failed: "+e.message,e)}).then(function(){return Uy(c)})})};Hz.prototype.X=function(){var a=this;return Qy(this.u,2,function(b){return new Promise(function(c,d){Az(a.m).then(function(){Uy(b,3);a.F=!0;Dj(a);c(a.R.bind(a))}).catch(function(e){a.jf("Failed to suspend MediaStreamer before starting remoting",e);d(e)})})})};
Hz.prototype.R=function(){var a=this;return Qy(this.u,3,function(b){return new Promise(function(c,d){a.m.resume().then(function(){Uy(b,2);a.F=!1;Dj(a);c()}).catch(function(e){a.jf("Failed resume MediaStreamer after ending remoting mode",e);d(e)})})})};var Mz=function(){Bj.call(this,"cast_streaming");this.D=this.C=this.J=this.H=this.l=null;this.Fb=this.M="";this.ea=this.u=!1;this.nd=this.Ba.bind(this);this.X=this.R=this.W=this.aa=this.m=null};t(Mz,Bj);k=Mz.prototype;k.Dg=function(a){this.u=a||!1;this.ea=!0};k.getName=function(){return"cast_streaming"};
k.qk=function(a,b,c,d,e){var f=this;if(!this.u)return Bj.prototype.qk.call(this,a,b,c,d,e);this.N.info("Start mirroring on route "+a.id);if(!this.ea)return Pi(Error("Not initialized"));var g=new Promise(function(h,m){f.o().then(function(){if(zj(b)&&c.shouldCaptureVideo)return gj(!1).then(function(q){f.Fb=q})}).then(function(){return e?e(a).promise:a}).then(function(q){f.M=b;Nz(f,q);var r=f.H.createInterfacePtrAndBind(),y=f.J.createInterfacePtrAndBind(),C=Oz(q,c);Pz(f,q,b,d);if(!f.l)throw new Ti("Error to get mirroring service host");
f.C=new mojo.MirroringCastMessageChannelPtr;f.aa=iy();f.l.start(C,r,y,mojo.makeRequest(f.C));f.m=new Nj(a,f.j.X.bind(f.j));Dj(f.m);Qz(f,q,b);f.R=function(){return h(q)};f.X=m}).catch(function(q){f.N.error("Mirroring launch error: "+q);f.Yf(void 0===q.reason?9:q.reason);m(q)})});return Qi(g)};k.Fh=function(a,b){return new Hz(a,b,20969472,null)};k.ih=function(){ky(0)};k.fh=function(){ky(1)};k.oi=function(){ky(2)};k.gh=function(){zb("MediaRouter.CastStreaming.Session.End")};
k.Yf=function(a){Ab("MediaRouter.CastStreaming.Start.Failure",a,Si)};k.hh=function(){zb("MediaRouter.CastStreaming.Stream.End")};
k.aj=function(a){var b=this;return this.u?Promise.resolve():(new Promise(function(c){return chrome.metricsPrivate.getIsCrashReportingEnabled(c)})).then(function(c){var d=c&&ry(),e=[9351424];d&&e.push(20969472);return Jz(a,e).then(function(f){var g=f[f.length-1];f=wm(f[0].events).catch(function(h){b.N.error("Failed to persist events Blob.",h)});d&&0<g.events.size?ny(g.events,void 0,b.Qv.bind(b)):c&&my("stats.json",g.dg,void 0,void 0);return f})})};
k.Qv=function(a){if(a){a=qy();var b=Date.now();a.g=b}};k.pk=function(a){if(this.u)return bb();this.N.info("Received message to upload logs for "+a);return this.g?Jz(this.g,[20969472]).then(function(b){b=n(b).next().value;return 0==b.events.size?"":ny(b.events,a)}):Promise.resolve(Rz(this,a))};
var Rz=function(a,b){var c=window.localStorage.getItem("mr.temp.mirror.cast.Service.eventsBlob");if(null==c||1>c.length)c=null;else{for(var d=new Uint16Array(c.length),e=0;e<c.length;++e)d[e]=c.charCodeAt(e);c=d.buffer;d=(new Uint8Array(c,c.byteLength-1,1))[0];c=new Uint8Array(c,0,c.byteLength-(0==d?2:1));c=new Blob([c],{type:"application/gzip"})}if(null!=c&&0!=c.size)return wm(new Blob),a.N.info("Uploading saved logs for feedback."),ny(c,b)};k=Mz.prototype;
k.onError=function(a){this.X&&(this.X(a),this.R=this.X=null,this.Yf(9));this.N.info("Mirroring service error: "+a);this.o()};k.didStart=function(){this.R&&(this.R(),this.R=this.X=null);this.aa&&(this.aa.end(),this.aa=null);this.W=jy();yj(this.M)?this.ih():zj(this.M)?this.fh():wj(this.M)&&this.oi()};k.didStop=function(){this.o()};k.send=function(a){if(this.D){var b=JSON.parse(a.jsonFormatData);lb(this.N,function(){return"Sending message: "+JSON.stringify(b)});this.D.sendMessage(a.jsonFormatData,{namespace:a.messageNamespace})}};
k.Rv=function(a){if(a&&(a.namespace_===mojo.MirroringWebRtcNamespace||a.namespace_===mojo.MirroringRemotingNamespace)&&this.C){var b=new mojo.MirroringCastMessage;b.messageNamespace=a.namespace_;"string"!==typeof a.data?this.N.info("Received non-string as JSON"):(b.jsonFormatData=a.data,this.C.send(b))}};
var Nz=function(a,b){a.H=new mojo.Binding(mojo.MirroringSessionObserver,a,null);a.J=new mojo.Binding(mojo.MirroringCastMessageChannel,a,null);a.D=cx(b.id);a.D.onMessage=a.Rv.bind(a)},Oz=function(a,b){var c=new mojo.MirroringSessionParameters;c.receiverAddress=new mojo.IPAddress;c.receiverAddress.addressBytes=a.tb.mh.split(".").map(function(d){return parseInt(d,10)});c.receiverModelName=a.tb.ze;a=Sz(a.mediaSource);c.targetPlayoutDelay=Tz(a);!b.shouldCaptureVideo||!b.shouldCaptureAudio||a&&"0"===a.searchParams.get("streamingCaptureAudio")?
c.type=b.shouldCaptureVideo?mojo.MirroringSessionType.VIDEO_ONLY:mojo.MirroringSessionType.AUDIO_ONLY:c.type=mojo.MirroringSessionType.AUDIO_AND_VIDEO;return c},Tz=function(a){if(!a)return null;a=Number(a.searchParams.get("streamingTargetPlayoutDelayMillis"));return isNaN(a)||0>=a?null:new mojo.TimeDelta({microseconds:1E3*a})},Sz=function(a){if(!a)return null;try{return new URL(a)}catch(b){return null}},Pz=function(a,b,c,d){a.l=new mojo.MirroringServiceHostPtr;b=b.tb.tabId||-1;yj(c)?a.j.getMirroringServiceHostForTab(b,
mojo.makeRequest(a.l)):zj(c)?a.j.getMirroringServiceHostForDesktop(-1,a.Fb,mojo.makeRequest(a.l)):wj(c)?(b=new mojo.Url,b.url=c,a.j.getMirroringServiceHostForOffscreenTab(b,d||"",mojo.makeRequest(a.l))):a.l=null},Qz=function(a,b,c){yj(c)&&!chrome.tabs.onUpdated.hasListener(a.nd)&&chrome.tabs.onUpdated.addListener(a.nd);(yj(c)||wj(c))&&Gj(a.m,b.tb.tabId)};Mz.prototype.Ba=function(a,b,c){vj(14);this.m&&Ij(this.m,a,b,c)};
Mz.prototype.o=function(){chrome.tabs.onUpdated.removeListener(this.nd);return this.u?this.ea?this.l?(this.l.ptr.reset(),this.C=this.l=null,this.D&&this.D.dispose(),this.D=null,this.H&&(this.H.close(),this.H=null),this.J&&(this.J.close(),this.J=null),Hj(this.j,this.m.h.id),this.m=null,this.Fb=this.M="",this.W&&(this.W.end(),this.W=null),this.gh(),Promise.resolve(!0)):Promise.resolve(!1):Promise.reject("Not initialized"):Bj.prototype.o.call(this)};
Mz.prototype.ka=function(a,b,c,d,e,f){return this.u?Pi(Error("Mirroring service does not support updating stream")):Bj.prototype.ka.call(this,a,b,c,d,e,f)};Mz.prototype.send=Mz.prototype.send;Mz.prototype.didStop=Mz.prototype.didStop;Mz.prototype.didStart=Mz.prototype.didStart;Mz.prototype.onError=Mz.prototype.onError;var Uz=new Mz;sj("mr.mirror.cast.Service",Uz);
