'use strict';Registry.require("crcrc helper statistics uri layout/default/htmlutil i18n layout/default/layout_helper".split(" "),()=>{const C=rea.FEATURES,z=Registry.get("crcrc").cr,f=Registry.get("crcrc").crc,D=Registry.get("helper"),u=Registry.get("layout/default/htmlutil"),W=Registry.get("statistics"),K=Registry.get("uri"),t=Registry.get("i18n"),X=Registry.get("layout"),L=Registry.get("layout/default/layout_helper"),v=L.images;let E=3;if(C.RUNTIME.MOBILE)try{window.matchMedia("(orientation: portrait)").matches&&
(E=1)}catch(w){}X.render(()=>{let w={},M;const ca=(c,a)=>{const d=[];if(a.sub_menu_item){if(a.tabId&&(M=a.tabId),a.items.length){var b=f("table","actiontable at_"+a.name,"actiontable-"+a.name);N(b,a.items);d.push(b)}}else if(b=null,a.image?b=u.createIcon(v.get(a.image),a.name,a.id,null,""):a.enabler&&(b=u.createIcon(v.get(w.enabled?"button_ok":"cancel"),a.name,a.uuid,null,"")),b&&d.push(b),a.url||a.urls){b=z("span",a.name,a.id,"urls");var h=a.urls||[a];for(var g=0;g<h.length;g++){const p=h[g];var e=
document.createElement("span"),k=void 0;p.social?(k=u.createSocialButtons(),$(e).addClass("social").append(k)):(e.textContent=p.name,k=a.urls?e:c,k.url=p.url,k.newtab=p.newtab);$(k).addClass("clickable").on("click auxclick",function(x){H(this.url||this.href,this.newtab||p.social);x.preventDefault()});b.appendChild(e);g<h.length-1&&(e=document.createElement("span"),e.textContent=" | ",b.appendChild(e))}d.push(b)}else if(a.globalhint)O(a.options);else if(a.button)b=f("span",a.display||"",a.name,a.id,
"bu",!0),b.textContent=a.name,c.key=a.id,c.warning=a.warning,c.reload=a.reload,c.data=a.data,c.addEventListener("click",function(){let p=!0;this.warning&&(p=Y(this.warning));p&&Z(this.key,{reload:this.reload,data:this.data})}),$(c).addClass("clickable"),d.push(b);else if(a.userscript){const p=f("table","",a.name,a.uuid,"tw");b=f("tr","",a.name,a.uuid,"tw_tr1");h=[b];g=f("div","clickable"+(a.active_count?"":" not_executed")+(a.deleted?" was_deleted":""),a.name,a.uuid,"ai");if(a.uuid){const x=[];k=
null;k=a.blacklisted||a.foisted?"enabler_warning":a.enabled?a.contexter?"enabler_enabled enabler_later":"enabler_enabled":"enabler_disabled";var q=a.blacklisted||a.foisted||(a.enabled?t.getMessage("Enabled"):t.getMessage("Disabled"));e=function(n){if(n&&(0!=n.button||n.ctrlKey||n.metaKey))return H(rea.extension.getURL("options.html")+"#nav="+this.key,!0),n.stopPropagation(),n.preventDefault(),!1;a.foisted?I(a.uuid,"whitewash",!0):I(a.uuid,"enabled",!a.enabled)};k=u.createEnabler(k,a.uuid,"enabled",
{append:"enabled",disabled:a.blacklisted||a.deleted,title:q},e);q=f("td","",a.name,a.uuid,"tw_td1");b.appendChild(q);q.appendChild(k);k=f("div","script_name",a.name,a.uuid,"name");k.textContent=t.getTranslation(a,"name");g.appendChild(k);g.uuid=a.uuid;g.key=a.uuid;if(!a.deleted&&!a.blacklisted){$(g).on("click auxclick",e);e=t.getMessage("Edit");q=u.createIcon(v.get("edit"),"",a.uuid,"edit_script",e);const n=f("span","clickable",a.name,a.uuid,"edit_script");n.setAttribute("title",e);n.textContent=
e;x.push({always_visible:!1,id:"edit_script",img:q,text:n,oc:function(l){H(rea.extension.getURL("options.html")+"#nav="+a.uuid,!0)}})}a.blacklisted||a.foisted?(c.setAttribute("title",a.blacklisted||a.foisted),$(g).addClass("crossedout")):k.title=a.active_count?t.getMessage("This_script_was_executed_0count0_times",a.active_count):a.all_time_active_count?t.getMessage("This_script_was_executed_0count0_times_but_is_not_active_anymore",a.all_time_active_count):t.getMessage("This_script_was_not_executed_yet");
e=f("td","",a.name,a.uuid,"tw_td2");b.appendChild(e);e.appendChild(g);a.nnew||a.system||!a.abuse||(g=u.createIcon(v.get("flag"),"",a.uuid,"issue",t.getMessage("Report_an_issue_to_the_script_hoster_")),e=f("span","clickable",a.name,a.uuid,"action_issue_expl"),e.textContent=t.getMessage("Report_an_issue_to_the_script_hoster_").split(/[\.\(]+/)[0],x.push({always_visible:!1,id:"action_issue_expl",img:g,text:e,oc:function(){P(a.uuid,"hoster")}}));a.nnew||a.system||!a.support||(g=u.createIcon(v.get("bug"),
"",a.uuid,"bug",t.getMessage("Report_a_bug")),e=f("span","clickable",a.name,a.uuid,"action_issue_expl"),e.textContent=t.getMessage("Report_a_bug"),x.push({always_visible:!1,id:"action_issue_expl",img:g,text:e,oc:function(){P(a.uuid,"author")}}));const Q={};a.active_urls&&a.active_urls.forEach(n=>{var l=K.parse(n).hostname;if(!Q[l]){Q[l]=!0;var m="/"+K.getRegExpFromMatch("*://*."+l+"/*",!0)+"/";if(!a.override||!a.override.use_excludes.includes(m)){l=t.getMessage("Exclude_0domain0",l);n=u.createIcon(v.get("no"),
"",a.uuid,"domain"+n,l);var r=f("span","clickable",a.name,a.uuid,"action_domain");r.setAttribute("title",l);r.textContent=l;x.push({always_visible:!1,id:"action_domain",img:n,text:r,oc:function(y){I(a.uuid,"add_excludes",[m])}})}}});if(a.menu_cmds){let n;try{n=new RegExp("^"+D.escapeForRegExp(a.name)+"[ -:+/]*")}catch(l){console.log(l)}a.menu_cmds.forEach(l=>{const m=f("span","clickable",a.name,a.uuid,"menucmd_"+a.id);m.setAttribute("title",a.name);const r=n?l.name.replace(n,""):l.name;m.textContent=
r;const y=()=>{aa(l.id,()=>{C.ACTIONMENU.CLOSE_ALLOWED&&window.close()})};if(l.accessKey){const A=l.accessKey[0].toUpperCase();if(ba(A,y,c)){const R=new RegExp(A,"i");let B=m.textContent.search(R);const F=[];-1==B&&(m.textContent+=" ("+A+")",B=m.textContent.search(R));F.push({text:m.textContent.substr(0,B)});F.push({text:m.textContent.substr(B,1),class:"underlined"});F.push({text:m.textContent.substr(B+1)});m.textContent="";F.forEach(J=>{const S=f("span",J.class||"",l.id,J);S.textContent=J.text;m.appendChild(S)})}else console.warn("Registering keyboard shortcut for '"+
l.name+"' failed")}x.push({always_visible:!0,id:a.id,img:u.createIcon(v.get(l.image),r,l.id,null,""),text:m,oc:y})})}if(!a.deleted&&x.length){const n=[];x.forEach(m=>{var r=a.uuid+m.id;const y=f("tr","scriptmenu"+(m.always_visible?" always_visible":""),a.name,a.uuid,"tw_tr1"),A=f("td","clickable",r,"tw_tdn",1,!0);r=f("td","clickable",r,"tw_tdn",2,!0);r.setAttribute("colspan","2");r.addEventListener("click",m.oc);r.appendChild([m.img,m.text]);y.appendChild([A,r]);n.push(y)});g=f("div","actionenablercol",
a.name,a.uuid,"actionenablercol");e=f("i","actionenabler ifdisabled clickable far fa-"+v.get("enabler"),a.name,a.uuid,"actionenabler");k=f("i","actionenabler ifenabled clickable far fa-"+v.get("enabler_enabled"),a.name,a.uuid,"actionenabler_enabled");$("body").get(0).addEventListener("click",()=>{$(p).removeClass("show_scriptmenu");l.removeClass("enabled")},!0);const l=$(g);$(e,k,g).click(m=>{l.toggleClass("enabled");$(p).toggleClass("show_scriptmenu");m.stopPropagation()});g.appendChild([e,k]);h=
h.concat(n);e=f("td","",a.name,a.uuid,"tw_td3");b.appendChild(e);e.appendChild(g)}}p.appendChild(h);d.push(p)}else b=z("span",a.name,a.id,"ai"),b.textContent=a.name,d.push(b);return d},N=(c,a,d)=>{Object.keys(a).forEach(b=>{b=a[b];if(!c)if(d[b.pos])b.items&&b.items.length&&$(d[b.pos]).show();else{console.warn("Warn(cAm): unknown pos "+b.pos);return}var h=c||d[b.pos];const g=h?z("tr",b.name,b.uuid||b.id,"outer"):null,e=ca(g,b);if(e&&e.length){h.appendChild(g);for(let k,q=0;k=e[q];q++){h=q==e.length-
1?3-q:0;const p=z("td","actiontd",b.name,b.uuid||b.id,q);0<h&&p.setAttribute("colspan",h);k&&p.appendChild(k);g.appendChild(p)}}})},T=(c,a)=>{(a=document.getElementById("action"))?a.innerHTML="":(a=z("div"),a.setAttribute("id","action"),a.setAttribute("class","action"),$(document.body).append(a,status));var d=f("table","actionlayout","actionlayout");a.appendChild(d);a=f("tr","actionpostr","hor");const b=f("td","actionpostd","hor_west");a.appendChild(b);d.appendChild(a);const h=f("table","actionregion noborder ar_top",
"top"),g=f("table","actionregion noborder ar_right","right");let e;const k=f("table","actionregion noborder ar_left","left"),q=f("table","actionregion noborder ar_bottom","bottom");if(2<Math.min(w.action_menu_columns,E)){e=f("table","actionregion noborder ar_center","center");const p=f("td","actionpostd","hor_center");d=f("td","actionpostd","hor_east");p.appendChild(e);a.appendChild(p);a.appendChild(d)}else 1<Math.min(w.action_menu_columns,E)?(e=g,d=f("td","actionpostd","hor_east"),a.appendChild(d)):
(e=k,d=b);$([e,g]).hide();b.appendChild(h);d.appendChild(g);b.appendChild(k);b.appendChild(q);N(null,c,{top:h,left:k,center:e,right:g,bottom:q})},H=(c,a)=>{try{const d=()=>{a&&C.ACTIONMENU.CLOSE_ALLOWED&&window.close()};a?sendMessage({method:"newTab",url:c},d):rea.tabs.getSelected(null,b=>{rea.tabs.sendMessage(b.id,{method:"loadUrl",url:c,newtab:a},d)})}catch(d){console.warn("lU:",d)}},Y=c=>{let a=confirm(c.msg),d={};a&&c.ok?d=c.ok:!a&&c.cancel&&(d=c.cancel);if(c.ok||c.cancel)a=!0;d.url&&sendMessage({method:"newTab",
url:d.url},b=>{});return a},O=c=>{let a;const d=c.key||"general";(a=U[d])&&$(a).remove();U[d]=u.createGobalHint(D.copy(c,{instant:!0}),document.getElementById("action"))},P=(c,a,d)=>{try{sendMessage({method:"reportAnIssue",uuid:c,to:a},b=>{d&&d()})}catch(b){console.warn("raI:",b)}},Z=(c,a)=>{try{sendMessage({method:"buttonPress",name:c,data:a.data},d=>{a.reload&&rea.page.reload()})}catch(d){console.warn("rSU:",d)}},G={},da=(c,a,d)=>{document.body.addEventListener("keydown",b=>{b.altKey||b.ctrlKey||
b.shiftKey||Object.keys(G).forEach(h=>{(h=G[h])&&b.keyCode==h.key&&h.cb.apply(h.elem||window,[])})},!1)},ba=(c,a,d)=>{c=c.charCodeAt(0);if(G[c])return console.log("MenuCmdKeyListener: ...failed!"),!1;G[c]={key:c,cb:a,elem:d};return!0},aa=(c,a)=>{try{sendMessage({method:"execMenuCmd",id:c},d=>{a&&a()})}catch(d){console.warn("Error(eMC):",d)}},I=(c,a,d)=>{try{c={method:"modifyScriptOptions",uuid:c},a&&""!=a&&(c[a]=d),sendMessage(c,b=>{document.getElementById("action").innerHTML="";b&&b.items&&(b.options&&
(w=D.assign(w,b.options)),T(b.items))})}catch(b){console.warn("Error(mSo): "+b.message)}},ea=(c,a)=>{const d=Date.now(),b=c.min_delay;sendMessage({method:"loadTree",referrer:c.referrer,layout:c.layout,available_columns:E,uuid:c.uuid,tabId:c.tabId},h=>{h.options&&(w=D.assign(w,h.options),w.statistics_enabled&&W.init("act",rea.extension.manifest.version,!0,!1,!0));const g=Date.now()-d,e=()=>{a(h)};!b||g>=b?a(h):window.setTimeout(e,b-g)})},U={};rea.extension.onMessage.addListener((c,a,d)=>{"update"==
c.method?V():"status"==c.method?(O(c.options),d({})):console.log('onMessage: Unknown method "'+c.method+'"')});const V=window.main=()=>{ea({referrer:"actions",min_delay:C.ACTIONMENU.MIN_DELAY,layout:!0,tabId:M},c=>{if(c.options&&c.options.layout_user_css){const a=document.createElement("style");a.innerHTML=c.options.layout_user_css;(document.head||document.body||document.documentElement||document).appendChild(a)}da();T(c.items,!0)})};L.addStyle(V)})});
