'use strict';window.requestFileSystem||(window.requestFileSystem=window.webkitRequestFileSystem);window.BlobBuilder||(window.BlobBuilder=window.WebKitBlobBuilder);
Registry.require("promise layout xmlhttprequest convert crcrc curtain layout/default/tabview layout/default/htmlutil helper i18n parser statistics layout/default/layout_helper".split(" "),()=>{const L=rea.FEATURES,Q=Registry.get("promise"),r=Registry.get("crcrc").cr,e=Registry.get("crcrc").crc,h=Registry.get("i18n"),R=Registry.get("curtain"),I=Registry.get("helper"),U=Registry.get("layout/default/tabview"),E=Registry.get("layout/default/htmlutil"),ca=Registry.get("statistics"),da=Registry.get("layout"),
V=Registry.get("layout/default/layout_helper"),M=V.images;da.render(()=>{let v=null,G={},W="???",S=null,X="0.0.0";const y=(b,a,c)=>{c=c||{};const d=Q();try{const f={aid:b,method:a};c.data&&I.each(c.data,(g,m)=>{f[m]=c.data[m]});sendMessage({method:"askCom",data:f},g=>{c.bg||R.hide();G=g.options||G;g.error?(g.please_close&&window.setTimeout(window.close,100),d.reject(g)):d.resolve(g)});c.bg||R.wait(h.getMessage("Please_wait___"))}catch(f){console.warn("sS: "+f.message),d.reject()}return d.promise()},
ea=()=>y(v.aid,"ping",{bg:!0}),fa=(b,a,c)=>{try{sendMessage(I.assign({method:"buttonPress",name:b},a),d=>{c&&c(d)})}catch(d){console.log("button: "+d.message)}},O=()=>{var b=e("div","content_wrapper","ask","main");$(document.body).append(b).addClass("main");var a=e("div","head_container","ask","head_container"),c=e("div","tv_container_fit","ask","tv_container");const d=r("a","head_link","ask","head_link");d.href="https://www.tampermonkey.net";d.target="_blank";const f=e("div","float","ask","head1"),
g=e("img","banner","ask");g.src=M.brand("tampermonkey");const m=e("div","float head","ask","head2"),p=e("div","header_title","heading"),t=e("div","version","version","version");t.textContent=" by Jan Biniok";const k=r("div","search","box","");p.innerHTML="Tampermonkey<sup>&reg;</sup>";f.appendChild(g);m.appendChild(p);m.appendChild(t);d.appendChild(f);d.appendChild(m);a.appendChild(d);a.appendChild(k);b.appendChild(a);b.appendChild(c);b=U.create("_main",c);a=r("div","main","main","tab_content_h");
a.textContent=W;c=r("div","main","main","tab_content");b.appendTab(I.createUniqueId("main","main"),a,c).select();b=c;R.hide();return b},ha=b=>{const a=b.script,c=b.oldscript,d=e("div","viewer_bottom_tab","bottom","");b={tv:"tv tv_alt",tv_table:"tv_table tv_table_alt",tr_tabs:"tr_tabs tr_tabs_alt",tr_content:"tr_content tr_content_alt",td_content:"td_content td_content_alt",td_tabs:"td_tabs td_tabs_alt",tv_tabs_align:"tv_tabs_align tv_tabs_align_alt",tv_tabs_fill:"tv_tabs_fill tv_tabs_fill_alt",tv_tabs_table:"tv_tabs_table tv_tabs_table_alt",
tv_contents:"tv_contents tv_contents_alt",tv_tab_selected:"tv_tab tv_selected tv_tab_alt tv_selected_alt",tv_tab_close:"",tv_tab:"tv_tab tv_tab_alt",tv_content:"tv_content tv_content_alt"};if(G.editor_enabled){const g=U.create("_source"+a.uuid,d,b);let m;const p=(k,l)=>{const z=e("div","tv_content tv_content_alt",k.uuid,l+"container_o");var w=e("table","editor_container_o editor_400p_container_o p100100 noborder",k.uuid,l+"container_o");const F=e("tr","editor_container p100100",k.uuid,l+"container");
z.appendChild(w);w.appendChild(F);w=e("td","editor_outer editor_400p_outer",k.uuid,l+"edit");k=e("div","editor_100 editor_border",k.uuid,l+"edit");F.appendChild(w);w.appendChild(k);return{c:z,e:k}};let t=()=>{const k=Q();rea.page.addStyle("vendor/cm/mode/diff/diff.css");Registry.vendor(["vendor/jsdiff/diff","vendor/cm/mode/diff/diff"],()=>{t=Q.Pledge;k.resolve()});return k.promise()};(()=>c&&c.textContent!=a.textContent?t().then(()=>{const k=r("div",a.uuid,"diff_h");k.textContent=h.getMessage("Changes");
const l=p(a,"diff");d.diff=new MirrorFrame(l.e,{theme:"diff",fontSize:G.editor_fontSize,value:h.getMessage("Please_wait___"),noButtons:!0,mode:"diff",readOnly:!0});m=g.appendTab("diff",k,l.c,()=>{window.setTimeout(()=>{d.diff.refresh();d.diff.mirror.focus()},1)});window.setTimeout(()=>{let z;try{z=window.JsDiff.createTwoFilesPatch(h.getMessage("Current_Version"),h.getMessage("New_Version"),c.textContent,a.textContent,void 0,void 0,{timeout:4E3})}catch(w){console.warn(w)}z||(z=h.getMessage("The_diff_for_this_script_is_too_large_to_render"));
d.diff.mirror.setValue(z)},500)}):Q.Pledge())().then(()=>{var k=r("div",a.uuid,"source_h");k.textContent=h.getMessage("Source_Code");const l=p(a,"source");d.editor=new MirrorFrame(l.e,{theme:G.editor_theme,fontSize:G.editor_fontSize,tabSize:Number(G.editor_tabSize),value:a.textContent,noButtons:!0,matchBrackets:!0,readOnly:!0});k=g.appendTab("source",k,l.c,()=>{window.setTimeout(()=>{d.editor.refresh();d.editor.mirror.focus()},1)});m=m||k}).then(()=>{m.select()})}else{var f=e("div","editor_400p_outer",
"editor",a.name);b=e("div","editor_400p editor_border","editor",a.name);d.appendChild(f);f.appendChild(b);f=e("textarea","editorta","editor",a.name);f.setAttribute("wrap","off");b.appendChild(f);f.value=a.textContent}return d},ia=(()=>{const b={};window.addEventListener("keydown",a=>{let c=!1;if("keydown"==a.type&&(b[a.keyCode]&&(c=b[a.keyCode](a)),c))return a.stopPropagation(),a.preventDefault(),!1},!0);return{registerListener:function(a,c){b[a]=c}}})(),J=(b,a,c)=>{I.select(c,d=>d.label).forEach(d=>
{const f=d.icon?E.createImageTextButton(d.id,d.id,d.label,d.icon,d.fn):E.createButton(d.label,d.id,d.label,d.fn),g=$(f);g.addClass(a);d.id&&g.attr("data-btn-id",d.id);b.appendChild(f);d.focus&&window.setTimeout(()=>{g.focus()},300);d.keyDown&&ia.registerListener(d.keyDown.keyCode?d.keyDown.keyCode:d.keyDown,d.keyDown.cb?d.keyDown.cb:d.fn)})},ka=b=>{const a=b.script,c=e("div","viewer_last","install"),d=e("div","viewer_content","install_content"),f=e("div","ask_action_buttons","install_buttons"),g=
[];g.push({label:b.messages.action,fn:function(){y(v.aid,"install")},focus:!0});L.RUNTIME.CHROME&&21>L.RUNTIME.BROWSER_VERSION&&g.push({label:b.messages.flags.install?h.getMessage("Process_with_Chrome"):null,fn:function(){ja(a.fileURL);$(c).hide()}});g.push({label:h.getMessage("Cancel"),fn:K,keyDown:27});J(f,"install",g);d.appendChild(f);c.appendChild(d);return c},la=b=>{const a=e("div","viewer_last","import");var c=e("div","viewer_content","import_content");const d=e("div","ask_action_buttons import_buttons",
"import_buttons");J(d,"import",[{label:h.getMessage("Import"),fn:function(){const f=Object.keys(b.scripts).filter(m=>!!$("input[type=checkbox][data-import-id="+m+"]:checked").val()),g=b.global_settings&&!!$("input[type=checkbox][data-import-id=global_settings]:checked").val();y(v.aid,"import",{data:{import_ids:f,global_settings:g}})},focus:!0},{label:h.getMessage("Cancel"),fn:K,keyDown:27}]);c.appendChild(d);a.appendChild(c);c=e("div","section","btn");c.appendChild(a);return c},ma=b=>{b=e("div","viewer_last",
"ok");const a=e("div","viewer_content","ok_content"),c=e("div","ask_action_buttons","ok_buttons");J(c,"import",[{label:h.getMessage("Ok"),fn:K,focus:!0}]);a.appendChild(c);b.appendChild(a);return b},na=(b,a)=>{const c=e("div","viewer_last","ok");var d=e("div","viewer_content","ok_content"),f=e("div","ask_action_buttons","ok_buttons");J(f,"permission",[{label:h.getMessage("Ok"),fn:()=>{const k={permissions:a.permissions,origins:a.origins};rea.permissions.request(k,l=>{let z;rea.runtime.lastError&&
(z=rea.runtime.lastError.message,console.warn("notify: error on getting permission",k,"reason:",z));y(v.aid,"permission",{data:{granted:l,permissions:k.permissions,origins:k.origins,error:z}})})},focus:!0},{label:h.getMessage("Cancel"),fn:K,keyDown:27}]);d.appendChild(f);c.appendChild(d);d=e("div","viewer_upper","permission");f=e("div","viewer_info viewer_info_wide","general","permission");const g=e("div","viewer_content","general_content","permission"),m=r("h3","install","heading","permission"),
p=r("span","install","heading_span","permission"),t=e("span","message","heading","permission");document.title=p.textContent=a.title;t.innerHTML=E.safeTagsReplace(a.message).replace(/\n/g,"<br>");m.appendChild(p);g.appendChild(t);f.appendChild(m);f.appendChild(g);d.appendChild(f);f=e("div","section","perm_src","permission");f.appendChild(d);f.appendChild(c);b.appendChild(f)},oa=(b,a)=>{const c=Date.now();let d,f;a.timeout&&(d=window.setTimeout(()=>{K();g()},a.timeout));const g=()=>{let n;f&&window.clearInterval(f);
d&&window.clearTimeout(d);f=d=null;(n=$("input[data-btn-id]")[0])&&n.parentNode.removeChild(n)},m=e("div","viewer_last","ok");var p=e("div","viewer_content","ok_content");const t=e("div","ask_action_buttons","ok_buttons"),k=e("div","ask_action_buttons","ok_buttons"),l=e("div","ask_action_buttons","ok_buttons");J(t,"connect",[{label:h.getMessage("Allow_once"),icon:"button_ok",fn:function(){return y(v.aid,"connect",{data:{ok:!0,allow:!0,once:!0}})},focus:!0},{label:h.getMessage("Temporarily_allow"),
icon:"clock",fn:function(){return y(v.aid,"connect",{data:{ok:!0,allow:!0,temporary:!0}})}},{label:a.hostname!=a.domain?h.getMessage("Always_allow"):h.getMessage("Always_allow_domain"),icon:"yes_domain",fn:function(){return y(v.aid,"connect",{data:{ok:!0,allow:!0}})}},(()=>a.domain&&a.hostname!=a.domain?{label:h.getMessage("Always_allow_domain"),icon:"yes_domain",fn:function(){return y(v.aid,"connect",{data:{ok:!0,allow:!0,whole_domain:!0}})}}:null)(),(()=>a.all_domains?{label:h.getMessage("Always_allow_all_domains"),
icon:"critical",fn:function(){g();if(window.confirm(h.getMessage("This_gives_this_script_the_permission_to_retrieve_and_send_data_from_and_to_every_webpage__This_is_potentially_unsafe__Are_you_sure_you_want_to_continue_")))return y(v.aid,"connect",{data:{ok:!0,allow:!0,all_domains:!0}})}}:null)()].filter(n=>n));J(k,"connect",[{label:h.getMessage("Forbid_once"),icon:"cancel",fn:function(){return y(v.aid,"connect",{data:{ok:!0,deny:!0,once:!0}})},keyDown:27},{label:a.hostname!=a.domain?h.getMessage("Always_forbid"):
h.getMessage("Always_forbid_domain"),icon:"no_domain",fn:function(){return y(v.aid,"connect",{data:{ok:!0,deny:!0}})}},(()=>a.domain&&a.hostname!=a.domain?{label:h.getMessage("Always_forbid_domain"),icon:"no",fn:function(){return y(v.aid,"connect",{data:{ok:!0,deny:!0,whole_domain:!0}})}}:null)(),{label:h.getMessage("Dont_ask_again"),icon:"no",fn:function(){return y(v.aid,"connect",{data:{ok:!0,deny:!0,all_domains:!0}})}}].filter(n=>n));J(l,"connect_misc",[(()=>a.tabid?{label:h.getMessage("Focus_tab"),
icon:"windowlist",fn:function(){fa("focus_tab",{tabid:a.tabid})}}:null)(),(()=>{if(a.timeout)return f=window.setInterval(()=>{let n;(n=$("input[data-btn-id]")[0])&&$(n).attr("value",h.getMessage("Skip_timeout__0seconds0_seconds_",Math.round((a.timeout+c-Date.now())/1E3)))},1E3),{label:h.getMessage("Skip_timeout__0seconds0_seconds_",Math.round(a.timeout/1E3)),id:"skip_timeout_button",fn:g}})()].filter(n=>n));const z=e("div","viewer_upper","connect"),w=e("div","viewer_info viewer_info_wide","general",
"connect"),F=e("div","viewer_content","general_content","connect"),q=r("h3","install","heading","connect"),A=r("span","install","heading_span","connect"),x=e("span","message","heading","connect");if(a.script.icon){var C=r("img","version","heading","connect");C.src=a.script.icon;A.appendChild(C)}document.title=A.textContent=h.getMessage("A_userscript_wants_to_access_a_cross_origin_resource_");C=e("div","ask_action_buttons message","help","connect");const D=r("div","help","connect");let u=h.getMessage("A_request_to_a_cross_origin_resource_is_nothing_unusual__You_just_have_to_check_whether_this_script_has_a_good_reason_to_access_this_domain__For_example_there_are_only_a_very_few_reasons_for_a_userscript_to_contact_your_bank__Please_note_that_userscript_authors_can_avoid_this_dialog_by_adding_@connect_tags_to_their_scripts__You_can_change_your_opinion_at_any_time_at_the_scripts_settings_tab_",
a.connect_url,a.settings_url);u=E.safeTagsReplace(u).replace(/\[url=([^\]]+)\](.*)\[\/url\]/g,'<a target="_blank" href="$1">$2 &#x2B00;</a>').replace(/\n/g,"<br>");D.innerHTML=u+"<br><br>";C.appendChild(D);q.appendChild(A);p.appendChild([l,C,t,k]);m.appendChild(p);const B=e("table","script_desc","connect");[{prop:"name",label:h.getMessage("Name")},{prop:"src_url",label:h.getMessage("Tab_URL")},a.domain?{prop:"hostname",label:h.getMessage("Destination_domain")}:null,{prop:"url",label:h.getMessage("Destination_URL")}].forEach(n=>
{if(n){var H=a[n.prop]||a.script[n.prop]||n.value,N=e("tr","script_desc",n.prop,"connect"),P=e("td","script_desc",n.prop,"connectdt"),Y=e("td","script_desc",n.prop,"connectdd");P.textContent=n.label?n.label:"";Y.textContent=H||h.getMessage("_not_set_");N.appendChild(P);N.appendChild(Y);B.appendChild(N)}});x.appendChild(B);F.appendChild(x);w.appendChild(q);w.appendChild(F);z.appendChild(w);p=e("div","section","connect_src","connect");p.appendChild(z);p.appendChild(m);b.appendChild(p)},qa=(b,a)=>{document.title=
h.getMessage("Import");b.appendChild(la(a));if(a.global_settings){const c=e("div","viewer_upper","");pa({content:c,checkbox:"import",key:"global_settings"});b.appendChild(c)}a.scripts&&Object.keys(a.scripts).forEach(c=>{const d=a.scripts[c],f=e("div","viewer_upper",c);T({content:f,preparat:d,checkbox:"import",key:c},!0);b.appendChild(f)})},Z=(b,a)=>{const c=r("input",b+"_",a,"",!0);c.setAttribute("data-import-id",a);c.checked=!0;c.type="checkbox";c.addEventListener("click",d=>{(d.ctrlKey||d.metaKey)&&
$("input[type=checkbox][data-import-id!="+a+"]").prop("checked",c.checked)});return c},pa=b=>{var a=b.key;const c=b.content,d=e("div","viewer_upper",a);var f=e("div","viewer_info viewer_info_wide","general",a);const g=e("div","viewer_content","general_content",a);var m=r("h3","install","heading",a);b.checkbox&&m.appendChild(Z(b.checkbox,b.key));b=r("img","version","heading",a);b.src=M.brand("tampermonkey");m.appendChild(b);b=r("span","name","heading",a);b.textContent=h.getMessage("Global_Settings");
m.appendChild(b);f.appendChild(m);m=e("table","script_desc",a);b=e("tr","settings_desc","action",a);let p=e("td","settings_desc","action",a+"dt"),t=e("td","settings_desc","action",a+"dd");p.textContent=h.getMessage("Action");t.textContent=h.getMessage("Global_settings_import");b.appendChild(p);b.appendChild(t);m.appendChild(b);b=e("tr","settings_desc","warning",a);p=e("td","settings_desc","warning",a+"dt");t=e("td","settings_desc","warning",a+"dd");a='<i class="far fa-'+M.get("critical")+'"></i>&nbsp;';
L.RUNTIME.MOBILE||(p.innerHTML=a,a="");t.innerHTML=a+E.safeTagsReplace(h.getMessage("This_will_overwrite_your_global_settings_"));b.appendChild(p);b.appendChild(t);m.appendChild(b);g.appendChild(m);f.appendChild(g);d.appendChild(f);f=e("div","section","settings_src");f.appendChild(d);c.appendChild(f)},T=(b,a)=>{const c=b.preparat,d=b.content,f=c.script||{},g=f.uuid||f.id||f.name;c.short_info||(c.short_info=[]);const m=e("div","viewer_upper",g);var p=e("div","viewer_info "+(a?"viewer_info_wide":"viewer_info_multiple"),
"general",g);const t=e("div","viewer_content","general_content",g);var k=r("h3","install","heading",g);b.checkbox&&k.appendChild(Z(b.checkbox,b.key));if(f.icon||f.icon64){var l=r("img","version","heading",g);l.src=f.icon||f.icon64;k.appendChild(l)}l=r("span","name","heading",g);l.textContent=c.heading||f.name||"";k.appendChild(l);f.version&&(l=e("span","view_version","heading",g),l.textContent="v"==f.version[0]?"":"v",l.textContent+=f.version,k.appendChild(l));p.appendChild(k);a&&c.short_info.unshift({prop:"heading",
value:c.messages.heading,label:h.getMessage("Action")});const z=e("table","script_desc",g);c.short_info.forEach(q=>{const A=f[q.prop]||q.value;if(A||!a){var x=e("tr","script_desc",q.prop,g),C=e("td","script_desc",q.prop,g+"dt"),D=e("td","script_desc",q.prop,g+"dd");C.textContent=q.label?q.label:"";D.textContent=A||h.getMessage("_not_set_");x.appendChild(C);x.appendChild(D);z.appendChild(x)}});t.appendChild(z);k=e("div","viewer_info viewer_info_multiple","info",g);let w;a?w=t:(w=e("div","viewer_content",
"info_content",g),l=r("h4","action","heading",g),document.title=l.textContent=c.messages.heading,w.appendChild(l));let F=0;["errors","warnings","info"].forEach(q=>{const A=r("table",q,g+F);(c.messages[q]||[]).forEach(x=>{F++;const C=r("tr",q,g+F),D=r("td",q,g+"dt"+F),u=r("td",q,g+"dd"+F);if("info"==q)if(x.label&&x.value)D.textContent=x.label,u.textContent=x.value;else{var B='<i class="far fa-'+M.get("info")+'"></i>&nbsp;';L.RUNTIME.MOBILE||(D.innerHTML=B,B="");u.innerHTML=B+E.safeTagsReplace(x).replace(/\n/g,
"<br />")}else"warnings"==q?(B='<i class="far fa-'+M.get("critical")+'"></i>&nbsp;',L.RUNTIME.MOBILE||(D.innerHTML=B,B=""),u.innerHTML=B+E.safeTagsReplace(x).replace(/\n/g,"<br />")):"errors"==q&&(B='<i class="far fa-'+M.get("error")+'"></i>&nbsp;',L.RUNTIME.MOBILE||(D.innerHTML=B,B=""),u.innerHTML=B+E.safeTagsReplace(x).replace(/\n/g,"<br />"));C.appendChild(D);C.appendChild(u);A.appendChild(C)});w.appendChild(A)});l=(q,A,x,C)=>{const D=r("table",q,g);let u=0;const B={};A.forEach(n=>{if(!(u>C||B[n])){B[n]=
!0;var H=e("tr",q+"desc",n,g+u),N=e("td",q+"desc",n,g+u+"dt"),P=e("td",q+"desc",n,g+u+"dd");N.innerHTML=0==u?E.safeTagsReplace(x.label):"&nbsp;";P.innerHTML=u==C?'<span title="'+E.safeTagsReplace(x.warning)+'">...!</span>':E.safeTagsReplace(n);H.appendChild(N);H.appendChild(P);D.appendChild(H);u++}});if(f.options&&(A=f.options.override&&f.options.override["use_"+q])&&A.length){A=e("tr",q+"desc","ovverride",g+u);const n=e("td",q+"desc","ovverride",g+u+"dt"),H=e("td",q+"desc","ovverride",g+u+"dd");
n.innerHTML=0==u?E.safeTagsReplace(x.label):"&nbsp;";H.innerHTML=E.safeTagsReplace(" ("+h.getMessage("overwritten_by_user")+")");A.appendChild(n);A.appendChild(H);D.appendChild(A)}w.appendChild(D)};l("includes",(f.includes||[]).concat(f.matches||[]),{label:h.getMessage("Include_s__"),warning:h.getMessage("Attention_Can_not_display_all_includes_")},5);l("excludes",f.excludes||[],{label:h.getMessage("Exclude_s__"),warning:h.getMessage("Attention_Can_not_display_all_excludes_")},3);p.appendChild(t);
k.appendChild(w);m.appendChild(p);m.appendChild(k);p=e("div","section",g,"install_src");p.appendChild(m);b.install&&p.appendChild(b.install(c));b.editor&&p.appendChild(b.editor(c));d.appendChild(p)},ja=b=>{y(v.aid,"abort");window.setTimeout(()=>{window.location=b+"#bypass=true"},10)};var K=b=>{y(v.aid,"abort");window.setTimeout(()=>{window.close()},3E3)};const aa=(b,a)=>{y(v.aid,"unload");S&&(window.clearInterval(S),S=null);window.removeEventListener("unload",aa)};window.addEventListener("unload",
aa);const ba=()=>{window.location.search||window.location.hash?(v=I.getUrlArgs(),v.aid?(y(v.aid,"preparat").done(b=>{b.ext&&b.ext.version&&(X=b.ext.version);if(b.options&&(b.options.statistics_enabled&&ca.init("ask",X,!0),b.options.layout_user_css)){const c=document.createElement("style");c.innerHTML=b.options.layout_user_css;(document.head||document.body||document.documentElement||document).appendChild(c)}W=h.getMessage("Install");let a=null;b.preparat&&("install"==b.type?a=()=>{T({content:O(),preparat:b.preparat,
install:ka,editor:ha})}:"install_error"==b.type?a=()=>{T({content:O(),preparat:b.preparat,install:ma},!0)}:"import"==b.type?a=()=>{qa(O(),b.preparat)}:"permission"==b.type?a=()=>{na(O(),b.preparat)}:"connect"==b.type&&(a=()=>{oa(O(),b.preparat)}),S=window.setInterval(ea,3E3),a&&window.setTimeout(()=>{a();var c,d;(c=b.preparat)&&(d=c.hints)&&d.length&&d.forEach(f=>{f.globalhint&&E.createGobalHint(f.options,$("body > div.status")[0])})},1))}).fail(()=>{K()}),R.wait(h.getMessage("Please_wait___"))):
K()):window.onhashchange=()=>{ba()}};rea.extension.onMessage.addListener((b,a,c)=>{G=b.options||G;if("confirm"==b.method)I.confirm(b.msg,d=>{c({confirm:d})});else if("showMsg"==b.method)I.alert(b.msg),c({});else return!1;return!0});V.addStyle(ba)})});
