'use strict';Registry.require(["crcrc","helper","layout/default/layout_helper"],()=>{const m=Registry.get("crcrc").cr,h=Registry.get("crcrc").crc,u=Registry.get("helper"),q=Registry.get("layout/default/layout_helper").images,r=(b,a,c,e)=>{const d=(e.uuid?e.uuid:"")+e.id;a.title=b;(b=w({after:{image:"help"},name:e.name,id:d}))&&c.appendChild(b)},t=(b,a,c,e,d,f)=>{b=h("i","far fa-"+b,a,c,e,!0);b.alt=d?b.title=d:a||e||c;b.key=c;b.name=a;f&&(a=b.getAttribute("class")||"",b.setAttribute("class",a+" clickable"),
b.addEventListener("click",f),b.href="#");return b},v=(b,a,c)=>{var e=(a.uuid?a.uuid:"")+a.id;const d=m("div",a.name,e,"input");d.key=a.id;const f=m("input",a.name,e,"input",!0);b=b.split("##");f.name=a.name;f.uuid=a.uuid;f.key=a.id;f.oldvalue=a.value;f.value=void 0!=a.value?a.value:"";f.type=a.password?"password":"text";f.setAttribute("spellcheck","false");a.placeholder&&f.setAttribute("placeholder",a.placeholder);c&&!f.inserted&&f.addEventListener("change",c);c=h("span","optiondesc",a.name,e,"s1");
e=m("span",a.name,e,"s2");c.textContent=b[0]+":";1<b.length&&(e.textContent=b[1]);d.appendChild(c);d.appendChild(f);d.appendChild(e);a.enabledBy&&d.setAttribute("name","enabled_by_"+a.enabledBy);return{elem:d,input:f}},x=(b,a,c)=>{b=h("input","button",a.name,(a.uuid?a.uuid:"")+a.id,"bu",!0);b.name=a.name;b.uuid=a.uuid;b.key=a.id;b.type="button";b.value=a.name;b.data=a.data;b.reload=a.reload;b.ignore=a.ignore||a.reload;b.warning=a.warning;a.enabledBy&&b.setAttribute("name","enabled_by_"+a.enabledBy);
!b.inserted&&c&&b.addEventListener("click",c);return b},y=(b,a,c,e)=>{let d;d=h("input","button",b,a,"bu",!0);d.name=b;d.key=a;d.type="button";d.value=c;!d.inserted&&e&&d.addEventListener("click",e);return d},w=(b,a)=>{var c=(b.uuid?b.uuid:"")+b.id;let e;if(e=b.after||b.validation){var d=b.validation?"validation":"help";a&&(d+=" clickable");d=h("span",d,b.name,c,d,!0);e.image&&(b=t(q.get(e.image),c,"after_icon"),c=[],e.opacity&&c.push("opacity: "+e.opacity),b.setAttribute("style",c.join(";")),d.appendChild(b));
d&&(a&&d.addEventListener("click",a),e.msg&&d.setAttribute("title",e.msg))}return d},z=b=>({"&":"&amp;","<":"&lt;",">":"&gt;"})[b]||b;Registry.register("layout/default/htmlutil","e1582c36",{getInfoFromUrl:b=>{if(-1!=b.search(/\/\^?(http(s|s\?|\.\+)?|\.\*):\/\/(\.\*)*\$?\/?$/)||-1!=b.search(/htt(ps|p):\/\/(\*\/\*|\*)*$/)||-1!=b.search(/\*:\/\/(\*\/\*|\*)*$/)||"*"==b)return{dom:"*",tld:"*"};0==b.search(/\//)&&(b=b.replace(/\([^\)]*\)[\?|\+|\*|\{[^\}]*]*/g,""),b=b.replace(/\[[^\]]*\][\?|\+|\*|\{[^\}]*]*/g,
""),b=b.replace(/^\/|\/$|\^|\$|\\\?.*|#.*|\?|\(|\)|\+|\\|\.\*|/g,""));b=b.replace(/^\*:\/\//,"http://");0!=b.search("http")&&(b="http://"+b);b=b.split("/");if(3>b.length)return null;b=b[2].split(".");if(2>b.length)return null;const a=b[b.length-1];let c=b[b.length-2];"*"!==c&&(c=c.replace(/\*/g,""));const e=[];for(let d=b.length-3;0<=d&&-1==b[d].search("\\*");d--)e.push(b[d]);return{tld:a,dom:c,subdom:e.reverse()}},getValue:b=>{let a=b.value;if("native"===b.valtype)if("undefined"===a)a=void 0;else if("null"===
a)a=null;else try{a=JSON.parse(a)}catch(c){}return a},safeTagsReplace:b=>b.replace(/[&<>]/g,z),addClass:(b,a)=>{let c=b.getAttribute("class")||"";-1==c.search(new RegExp("[ \t]*"+a+"[ \t]*"))&&(c=(c?c+" ":"")+a);b.setAttribute("class",c)},toggleClass:(b,a)=>{let c=b.getAttribute("class")||"";const e=new RegExp("[ \t]*"+a+"[ \t]*");c=-1!=c.search(e)?c.replace(e,""):(c?c+" ":"")+a;b.setAttribute("class",c)},setHelp:r,createAfterIcon:w,createEnabler:(b,a,c,e,d)=>{const f=e.disabled,g=e.title,k=h("div",
"enabler "+b,a,c+"_enabler",e.append,"wrap",!0);b=h("i","far fa-toggle-on on green",a,c+"toggle-on");e=h("i","far fa-toggle-on fa-flip-horizontal off greyed",a,c+"toggle-off");k.appendChild([b,e]);g&&(k.title=g);k.key=c;k.uuid=a;f||k.addEventListener("click",()=>{$(k).hasClass("enabler_enabled")?$(k).removeClass("enabler_enabled"):$(k).addClass("enabler_enabled");d&&window.setTimeout(()=>{d.call(k)},100)});return k},createImage:(b,a,c,e,d,f)=>{const g=h("img","icon16",a,c,e,!0);g.setAttribute("src",
b);f&&(b=g.getAttribute("class")||"",g.setAttribute("class",b+" clickable"));g.alt=d?g.title=d:a||e||c;g.key=c;g.name=a;f&&(g.addEventListener("click",f),g.href="#");return g},createIcon:t,createFavicon:(b,a,c,e)=>{const d=h("img","icon16",a,c,u.filter(e,/[a-zA-Z0-9]/g));if(d.inserted)return d;"Array"!==u.toType(b)&&(b=[b]);const f=()=>{if(0!=b.length){var g=b.shift();"function"==typeof g?window.setTimeout(()=>{d.parentNode&&(d.parentNode.insertBefore(t(g(),a+"_ico",c,e),d),d.parentNode.removeChild(d))},
1):(d.setAttribute("src",g),d.setAttribute("async","true"))}};d.addEventListener("error",f);f();d.alt=e?d.title=e:a;return d},createFileInput:(b,a,c)=>{b=h("input","import","file",null,null,!0);b.inserted||(b.type="file",c&&b.addEventListener("change",c));return b},createNamedSettings:(b,a,c)=>{const e=(a.uuid?a.uuid:"")+a.id,d=h("div","settingsta",a.name,e,"named_wrapper"),f=h("div","named",a.name,e,"named_settings"),g=[],k=m("span",a.name,e,"s1");b&&(k.textContent=b+":");a.desc&&r(a.desc,k,k,a);
d.appendChild(k);d.appendChild(f);d.key=a.id;a.value.forEach(p=>{const n=h("div","",a.name+p.name,e,"named",!0);var l=h("div","",a.name+p.name,e,"named_label",!0);l.textContent=p.name;n.appendChild(l);l=m("textarea",a.name+p.name,e,"textarea",!0);l.setAttribute("spellcheck","false");l.name=a.name;l.key=a.id;l.named_name=p.name;l.uuid=a.uuid;l.named=!0;l.oldvalue=p.value||"";l.value=p.value||"";c&&!l.inserted&&l.addEventListener("change",c);n.appendChild(l);f.appendChild(n);g.push(l)});return{elem:d,
textareas:g,label:k}},createTextarea:(b,a,c)=>{const e=(a.uuid?a.uuid:"")+a.id,d=m("div",a.name,e,"textarea");d.key=a.id;const f=h("textarea","settingsta",a.name,e,"textarea",!0);f.setAttribute("spellcheck","false");f.name=a.name;f.key=a.id;f.uuid=a.uuid;f.json=a.json;f.array=a.array;f.oldvalue=a.value;f.value=void 0===a.value||null===a.value?"":a.array?a.value.join("\n"):a.json?JSON.stringify(a.value,null,4):a.value;c&&!f.inserted&&f.addEventListener("change",c);c=m("span",a.name,e,"s1");b&&(c.textContent=
b+":");a.desc&&r(a.desc,c,c,a);d.appendChild(c);d.appendChild(f);return{elem:d,textarea:f,label:c}},createFileSelect:(b,a,c)=>{const e=(a.uuid?a.uuid:"")+a.id,d=m("input",a.name,e,"file");var f=g=>{c(g.target.files)};d.inserted||(d.type="file",d.addEventListener("change",f,!1));return b?(f=m("div",a.name,e,"input"),a=m("span",a.name,e,"s1"),a.textContent=b+":",f.appendChild(a),f.appendChild(d),{elem:f,input:d}):{elem:d}},createInput:v,createColorChooser:(b,a,c)=>{const e=(a.uuid?a.uuid:"")+a.id;b=
v(b,a,c);const d=function(){c&&c.apply(this,arguments);const g=(this.value.match(/[a-fA-F0-9]+/)||"")[0];g&&[3,6].includes(g.length)&&f.setAttribute("style","background-color: #"+g+";")};b.input.inserted||b.input.addEventListener("keyup",d);const f=h("span","color_choosed",a.name,e,"col");b.col=f;b.elem.appendChild(b.col);d.call(b.input);return b},createPassword:(b,a,c)=>{b=v(b,a,c);b.input.setAttribute("type","password");return b},createCheckbox:(b,a,c)=>{const e=(a.uuid?a.uuid:"")+a.id,d=h("div",
"checkbox",a.name,e,"cb1");d.key=a.id;const f=m("input",a.name,e,"cb",!0);f.title=a.desc?a.desc:"";f.name=a.name;f.uuid=a.uuid;f.key=a.id;f.reload=a.reload;f.warning=a.warning;f.oldvalue=a.enabled;f.checked=a.enabled;f.type="checkbox";f.valtype="boolean";c&&!f.inserted&&f.addEventListener("click",c);c=h("span","checkbox_desc",a.name,e,"cb2");c.textContent=b;a.desc&&r(a.desc,d,c,a);d.appendChild(f);d.appendChild(c);return{elem:d,input:f}},createDropDown:(b,a,c,e,d)=>{const f=(a.uuid?a.uuid:"")+a.id,
g=m("div",a.name,f,"outer_dd");g.key=a.id;const k=m("select",a.name,f,"dd",!0);let p=!1;c&&Object.keys(c).forEach(n=>{const l=m("option",a.name,c[n].name,"dd"+f,!0);l.textContent=u.decodeHtml(c[n].name);l.value=c[n].value;l.warning=c[n].warning;p|=!!c[n].warning;c[n].enabledBy&&l.setAttribute("name","enabled_by_"+c[n].enabledBy);a.enabler&&c[n].enable&&l.setAttribute("enables",JSON.stringify(c[n].enable));c[n].value==a.value&&(l.selected=!0);k.appendChild(l)});k.key=a.id;k.name=a.name;k.uuid=a.uuid;
k.reload=a.reload;k.warning=a.warning;k.oldvalue=a.value;k.valtype="native";k.inserted||(e&&k.addEventListener("change",e),p&&d&&k.addEventListener("change",d));null!==b&&(e=h("span","optiondesc",a.name,f,"inner_dd"),e.textContent=b+": ",g.appendChild(e));g.appendChild(k);a.desc&&r(a.desc,g,g,a);a.enabledBy&&g.setAttribute("name","enabled_by_"+a.enabledBy);return{elem:g,select:k}},createImageButton:(b,a,c,e,d)=>{let f,g;f=h("button","imgbutton button",b,a,"bu",!0);g=h("div","imgbutton_container",
b,a,"bu_container");g.appendChild(f);f.uuid=b;f.key=a;b=h("i","imgbutton_image far fa-"+e,b,a,"bu_img",!0);f.appendChild(b);f.title=b.title=b.alt=c;!f.inserted&&d&&f.addEventListener("click",d);return g},createImageTextButton:(b,a,c,e,d)=>{const f=h("button","button imgtextbutton",b,a+c,"itb",!0);f.key=a;f.uuid=b;e&&(e=t(q.get(e),b,a+c+"itb",e),f.appendChild(e));b=m("span",b,a+c,"itb");b.textContent=c;f.appendChild(b);d&&f.addEventListener("click",d);return f},createButton:function(b,a,c,e){return"Object"===
u.toType(a)?x.apply(this,arguments):y.apply(this,arguments)},createPosition:(b,a,c)=>{const e=(a.uuid?a.uuid:"")+a.id,d=m("div",a.name,e,"pos1"),f=m("select",a.name,e,"pos",!0);for(let g=1;g<=a.posof;g++){const k=m("option",a.name,e,"opt"+g);k.textContent=g;g==a.pos&&(k.selected=!0);f.appendChild(k)}f.key=a.id;f.uuid=a.uuid;f.name=a.name;c&&!f.inserted&&f.addEventListener("change",c);a=h("span","optiondesc",a.name,e,"pos2");a.textContent=b;d.appendChild(a);d.appendChild(f);return d},createSearchBox:b=>
{const a=h("div","searchbox","search_inner"),c=h("div","searchbox_mv","search_inner_mv"),e=h("input","searchbox_input","search_input"),d=h("input","searchbox_button","search_button");e.type="text";e.setAttribute("spellcheck","false");e.value=b;d.type="button";d.value="Go";const f=()=>{window.location=window.location.origin+window.location.pathname+"?url="+encodeURIComponent(e.value)};d.addEventListener("click",f);e.addEventListener("keyup",g=>{g&&13==g.keyCode&&f()});c.appendChild(e);c.appendChild(d);
a.appendChild(c);return a},createSocialButtons:()=>{const b=[];var a=h("a","","github_link");a.href="https://github.com/derjanb";a.target="_blank";var c=h("img","icon16","github");c.setAttribute("src",q.origin("gh"));a.appendChild(c);b.push(a);a=h("a","","facebook_link");a.href="https://www.facebook.com/tampermonkey";a.target="_blank";c=h("img","icon16","facebook");c.setAttribute("src",q.brand("facebook"));a.appendChild(c);b.push(a);a=h("a","","insta_link");a.href="https://www.instagram.com/der_jan_b/";
a.target="_blank";c=h("img","icon16","instagram");c.setAttribute("src",q.brand("instagram"));a.appendChild(c);b.push(a);return b},createGobalHint:(b,a)=>{var c="global_hint_"+(b.class?b.class:"warning");const e=Date.now(),d=h("span",["global_hint",c].join(" "),"globalhint",e);c=m("span","globalhint_c",e);const f=m("span","globalhint_t",e);b.title&&(f.title=b.title);b.image&&c.appendChild(t(q.get(b.image),"globalhint_"+e,"icon"+e));f.textContent=b.text;b.onclick&&!f.inserted&&f.addEventListener("click",
b.onclick);c.appendChild(f);d.appendChild(c);const g=$(d);b.instant||(g.hide(),window.setTimeout(()=>{g.slideDown()},b.delay?b.delay:1));b.timeout&&window.setTimeout(()=>{b.instant?(g.hide(),g.remove()):g.slideUp(()=>{g.remove()});b.done&&b.done(d)},b.timeout);g.prependTo(a||document.body);return g},isScrolledIntoView:(b,a)=>{b=$(b);var c=$(window);a=a&&a.padding||0;const e=c.scrollTop();c=e+c.height();const d=b.offset().top;return d+b.height()<=c-a&&d>=e+a}})});
