'use strict';Registry.require(["crcrc","helper","promise"],()=>{const w=Registry.get("helper"),x=Registry.get("crcrc").cr,n=Registry.get("crcrc").crc,T=Registry.get("promise"),d={};Registry.register("layout/default/tabview","e1582c36",{create:(A,p,h,U)=>{const a=w.filter(A,/[0-9a-zA-Z]/g);A=!1;void 0==h&&(h={tv:"tv",tv_table:"tv_table",tr_tabs:"tr_tabs",tr_content:"tr_content",td_content:"td_content",td_tabs:"td_tabs",tv_tabs_fill:"tv_tabs_fill",tv_tabs_table:"tv_tabs_table",tv_tabs_align:"tv_tabs_align",
tv_contents:"tv_contents",tv_tab_selected:"tv_tab tv_selected",tv_tab_close:"tv_tab_close",tv_tab:"tv_tab",tv_content:"tv_content"});const F=n("div",h.tv,"main"+a),y=n("table",h.tv_table+" noborder","main_table"+a);y.inserted?A=!0:(d[a]={},d[a].g_entries={},d[a].g_selectedId=null);const G=n("tr",h.tr_tabs,"tabs"+p.id+a),H=n("td",h.td_tabs,"pages"+a),I=n("div",h.tv_tabs_fill,"tv_tabs_fill"+a),J=n("div",h.tv_tabs_table,"tv_tabs_table"+a),q=n("div",h.tv_tabs_align,"tv_tabs_align"+a),K=n("tr",h.tr_content,
"content"+p.id+a),L=n("td",h.td_content,"content"+a),D=n("div",h.tv_contents,"tv_content"+a),M=x("tfoot","tv_footer_t"+a),N=x("tr","tv_footer_tr"+a),O=x("td","tv_footer_td"+a);M.appendChild(N);N.appendChild(O);J.appendChild(q);I.appendChild(J);H.appendChild(I);G.appendChild(H);y.appendChild(G);L.appendChild(D);K.appendChild(L);y.appendChild(K);y.appendChild(M);F.appendChild(y);p.appendChild(F);const B=(b,e,c)=>{e?b.setAttribute("style",c?w.staticVars.visible_move:w.staticVars.visible):b.setAttribute("style",
c?w.staticVars.invisible_move:w.staticVars.invisible);b.setAttribute("vis",e.toString())},P=(b,e)=>{b=b.getId();d[a].g_entries[b]&&e!=d[a].g_entries[b].visible&&(d[a].g_entries[b].visible=e,B(d[a].g_entries[b].tab,e))},Q=(b,e)=>{b&&B(b.content,e,!1)},V=b=>{const e=Object.keys(d[a].g_entries);for(let c,g=0;c=e[g];g++){const k=d[a].g_entries[c];if(k.tab.id==b.id)return k}return null},z=b=>{if(null===b)return null;const e=Object.keys(d[a].g_entries);for(let c,g=0;c=e[g];g++){const k=d[a].g_entries[c];
if(k.entry.getId()==b)return k.entry}return null},W=b=>{if(b.getId()!=d[a].g_selectedId){var e=b.getId();d[a].g_selectedId&&Q(d[a].g_entries[d[a].g_selectedId],!1);Object.keys(d[a].g_entries).forEach(c=>{c=d[a].g_entries[c];c.entry.getId()==e?c.visible?c.selected||(c.tab.setAttribute("class",h.tv_tab_selected),c&&B(c.content,!0,!1),c.selected=!0):console.log("tv: WARN: tab selected but not visible!"):c.selected&&(c.tab.setAttribute("class",h.tv_tab),c&&B(c.content,!1,!1),c.selected=!1)});d[a].g_selectedId=
e}},R=b=>{b.hide();b=b.getId();if(b=d[a].g_entries[b]){b.tab.parentNode.removeChild(b.tab);b.content.parentNode.removeChild(b.content);a:{b=b.tab;const e=Object.keys(d[a].g_entries);for(let c,g=0;c=e[g];g++)if(d[a].g_entries[c].tab.id==b.id){b=c;break a}b=null}b&&delete d[a].g_entries[b]}else console.log("tv: WARN: tab not part of tabview!")};p=null;A?p=d[a].tv:(p={getTabById:z,getSelectedTab:function(){return z(d[a].g_selectedId)},getAllTabs:function(){const b=$(q).find("div[tvid]");let e,c;const g=
[];b.each((k,r)=>{(e=$(b.get(k)).attr("tvid"))&&(c=z(e))&&g.push(c)});return g},getNextTab:function(b){const e=$(q).find("div[tvid]");let c;d[a].g_selectedId&&e.each((g,k)=>{c||$(k).attr("tvid")===d[a].g_selectedId&&(c=$(e.get(g+1)).attr("tvid"))});return z(c||e.first().attr("tvid"))},getPreviousTab:function(b){const e=$(q).find("div[tvid]");let c;d[a].g_selectedId&&e.each((g,k)=>{c||$(k).attr("tvid")===d[a].g_selectedId&&(c=$(e.get(g-1)).attr("tvid"))});return z(c||e.last().attr("tvid"))},removeTab:R,
appendTab:function(b,e,c,g,k){return this.insertTab(void 0,b,e,c,g,k)},insertTab:function(b,e,c,g,k,r){null===b&&(b=q.firstChild);var t="tab_"+e;const l=x("div",t,"content"+a);var u=void 0!==l.inserted&&1==l.inserted;const X=x("div",t,"head_text"+a);c.appendChild(X);r&&(t=n("div",h.tv_tab_close,t,"tv_close"+a,"tab_close"),t.inserted||t.addEventListener("click",()=>{r()}),c.appendChild(t));if(u){if(u=V(l))return u.entry;console.log("tv: WARN: old tab, but not in tabs collection!")}let v;u=f=>{""!=
f.target.className&&f.target.className==h.tv_tab_close||v.select()};l.setAttribute("tvid",e);l.addEventListener("click",u);c.addEventListener("click",u);l.setAttribute("name","tabview_tab"+a);l.setAttribute("class",h.tv_tab);l.appendChild(c);b?q.insertBefore(l,b):q.appendChild(l);g.setAttribute("name","tabview_content"+a);g.setAttribute("class",h.tv_content);D.appendChild(g);v={getId:function(){return e},isVisible:function(){return"true"==l.getAttribute("vis")},isSelected:function(){return d[a].g_selectedId==
this.getId()},isCloseable:function(){return!!r},modified:function(){return $(c).hasClass("modified")},remove:function(){R(this)},hide:function(){var f=this.getId(),m=f==d[a].g_selectedId;d[a].g_entries[f]?P(this,!1):console.log("tv: WARN: tab not part of tabview!");if(m){m=f=null;for(const C in d[a].g_entries)d[a].g_entries[C].visible&&(f=d[a].g_entries[C],m||f.closable||(m=f));U||f.closable||(f=m);f?f.entry.select():(d[a].g_selectedId=null,console.log("tv: WARN: selected tab set, but entry collection empty!"))}},
show:function(){{const f=this.getId();d[a].g_entries[f]?P(this,!0):console.log("tv: WARN: tab not part of tabview!")}},select:function(f){if(f||!v.isSelected())f=T(),k&&k(f.promise()),W(this),f.resolve()},setHeading:function(f,m,C){const E=c.firstChild;if(m&&f.length>m){const S=Math.round(m/2);E.textContent=f.substr(0,S)+"..."+f.substr(S-m);E.title=C||f}else E.textContent=f},toggleClass:function(f,m){$(c,D).toggleClass(f,m)},close:function(){r&&r()}};d[a].g_entries[e]={entry:v,tab:l,content:g,closable:null!=
r};Q(d[a].g_entries[e],!1);v.show();return v},setFooter:function(b){O.appendChild(b)}},d[a].tv=p);return p}})});
