'use strict';Registry.require("convert",()=>{const r=Registry.get("convert"),n=(c,a)=>{void 0==a&&(a=[]);a=new RegExp("(\\"+"/.+?|()[]{}\\".split("").concat(a).join("|\\")+")","g");return c.replace(a,"\\$1")},h=c=>({}).toString.apply(c).match(/\s([a-z|A-Z]+)/)[1],k=(c,a)=>{var b=h(c);if("Array"===b||"NodeList"===b)for(b=0;b<c.length&&!1!==a(c[b],b);b++);else if("XPathResult"===b)for(b=c.iterateNext();b&&!1!==a(b);)b=c.iterateNext();else for(const d in c)if(c.hasOwnProperty(d)&&!1===a(c[d],d))break},
m=(c,a,b,d)=>{if("Array"===h(b)){const e={};b.forEach(f=>{e[f]=!0});b=e}k(b||c,(e,f)=>{if(!b||b.hasOwnProperty(f)){let g;e=c[f];const l=h(e);"Undefined"==l||b&&d&&(g=h(b[f]))&&g!==l&&("Array"===g||"Object"===g)||("Object"==l?(a[f]={},m(e,a[f],b?b[f]:null)):"Array"==l?(a[f]=[],m(e,a[f])):a[f]=e)}});return a},p=c=>document.body?document.body.innerText:0<c.childNodes.length?p(c.childNodes[c.childNodes.length-1]):c.innerText,t=(()=>{const c={objs:{},push:function(a,b){0!==b&&1!==b&&(b=0);const d=q();
c.objs[d]={fn:a,prio:b};return d},remove:function(a){delete c.objs[a]},get:function(a){const b=[];for(let d=0;1>=d;d++)for(const e in c.objs)c.objs.hasOwnProperty(e)&&(c.objs[e].prio!==d||void 0!==a&&e!=a||b.push(c.objs[e].fn));return void 0===a?b:b[0]},finalize:function(a){if(void 0===a){a=c.get();for(var b=0;b<a.length;b++)a[b]()}else return c.objs[a]&&(b=c.objs[a].fn(),delete c.objs[a]),b}};return c})();var q=()=>"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,c=>{const a=16*Math.random()|
0;return("x"==c?a:a&3|8).toString(16)});Registry.register("helper","e1582c36",{createUniqueId:(c,a)=>r.Base64.encode(c+"_"+a).replace(/[^0-9a-zA-Z_\-]/g,""),getStringBetweenTags:(c,a,b)=>{const d=c.indexOf(a);if(-1==d)return"";if(!b)return c.substr(d+a.length);b=c.substr(d+a.length).indexOf(b);return-1==b?"":c.substr(d+a.length,b)},escapeForRegExpURL:n,escapeForRegExp:(c,a)=>n(c,["*"]),isLocalImage:c=>{let a=rea.extension.getURL("background.js");a=a.replace("background.js","")+"images/";
return c.length>=a.length&&a==c.substr(0,a.length)},getUrlArgs:c=>{const a={};var b=window.location.search.replace(/^\?/,""),d=window.location.hash.replace(/^#/,"");b?c&&d&&(b=b+"&"+d):b=d;c=b.split("&");for(b=0;b<c.length;b++){var e=c[b].split("=");2!=e.length&&(d=e[0],e=e.slice(1).join("="),e=[d,e]);a[e[0]]=decodeURIComponent(e[1])}return a},getSource:p,alert:c=>{window.setTimeout(()=>{alert(c)},1)},confirm:(c,a)=>{window.setTimeout(()=>{const b=confirm(c);a(b)},1)},prompt:(c,a,b)=>{window.setTimeout(()=>
{const d=prompt(c,a);b(d)},1)},filter:(c,a)=>c&&a?(c.match(a)||[]).join(""):"",toType:h,splitSlice:(c,a)=>{const b=[];for(let d=0,e=c.length;d<e;d+=a)b.push(c.slice(d,a+d));return b},each:k,select:(c,a)=>{const b=[];k(c,d=>{a(d)&&b.push(d)});return b},map:(c,a)=>{const b=[];k(c,(d,e)=>{b.push(a(d,e))});return b},values:c=>(Object.values||(a=>Object.keys(a).map(b=>a[b])))(c),insert:(c,a,b,d)=>c.slice(0,a)+d+c.slice(a+Math.abs(b)),assign:(c,a)=>{c=c||{};Object.keys(a).forEach(b=>{c[b]=a[b]});return c},
clean:t,sleep:c=>{const a=Date.now();for(;Date.now()-a<c;)for(let b=0;100>b;b++);},copy:m,adiff:(c,a,b)=>{b=b||"both";const d=[];"both"==b?c.concat(a).forEach(e=>{c.includes(e)&&a.includes(e)||d.push(e)}):"notinfirst"==b&&a.forEach(e=>{c.includes(e)||d.push(e)});return d},getDebouncer:c=>(()=>{let a={};const b=c||1E3,d={clear:function(){k(a,(e,f)=>{window.clearTimeout(e)});a={}},is:function(e,f){const g=!!a[e];f&&d.add(e);return g},add:function(e,f){d.is(e)&&window.clearTimeout(a[e]);a[e]=window.setTimeout(()=>
{delete a[e]},f||b)}};return d})(),createUUID:q,decodeHtml:c=>c.replace(/(?:&#x([a-fA-F0-9]+);|&#([0-9]+);)/g,(a,b,d)=>b?String.fromCharCode(parseInt(b,16)):String.fromCharCode(parseInt(d,10))),encodeHtml:c=>c.replace(/[\u00A0-\u2666<>]/g,a=>"&#"+a.charCodeAt(0)+";"),safeFileName:(c,a,b)=>{void 0===b&&(b="-");var d=a?/[:<>|~?*\x00-\x1F\uFDD0-\uFDEF"]/g:/[:<>|~?*\x00-\x1F\uFDD0-\uFDEF"\/\\]|^[.]|[.]$/g,e=/^((CON|PRN|AUX|NUL|CLOCK\$|COM[1-9]|LPT[1-9])(\..*)?|device(\..*)?|desktop.ini|thumbs.db)$/i;
return!a&&e.test(this)?(b||"_")+c.replace(d,b):c.replace(d,b)},staticVars:{visible:void 0,invisible:"display: none;",visible_move:void 0,invisible_move:"position:absolute; left: -20000px; top: -200000px; width: 1px; height: 1px;"}})});
