'use strict';Registry.require(["promise","icon","helper"],()=>{const p=Registry.log,w=Registry.get("promise"),A=Registry.get("icon"),z=Registry.get("helper"),u=rea.FEATURES,B=(()=>{const a={};let e=null,f=0,g;const h={init:function(){if(g)return g;const m=w(),t=c=>{e=c||"unknown";p.log("notify: chronos level",c);m.resolve()};rea.notifications.supported?(rea.notifications.getPermissionLevel(t),rea.notifications.onPermissionLevelChanged.addListener(t),rea.notifications.onClicked.addListener(c=>{p.log("notify: chronos click",
c);a[c]&&(a[c].cb.click&&a[c].cb.click(),a[c].cancel(),delete a[c])}),rea.notifications.onClosed.addListener(c=>{p.log("notify: chronos close",c);a[c]&&a[c].cb.close&&a[c].cb.close();delete a[c]})):t("unsupported");return g=m.promise()},create:function(m,t,c,q){return h.init().then(()=>{const r=w();let l=10;const k=()=>{if(e)if("granted"==e){const d={nid:null,cb:{},on:function(n,b){d.cb[n]=b},cancel:function(){},show:function(){const n={type:"basic",title:t||"",message:c||""};n.iconUrl=0==f?m:"data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==";
(u.RUNTIME.CHROME&&70<=u.RUNTIME.BROWSER_VERSION||u.RUNTIME.SAFARI)&&void 0!==q.silent&&(n.silent=q.silent);u.RUNTIME.CHROME&&50<=u.RUNTIME.BROWSER_VERSION&&(n.requireInteraction=!0);const b=z.createUUID();rea.notifications.create(b,n,()=>{rea.runtime.lastError?1>f?(p.log("notify: chronos creating failed, retry...",rea.runtime.lastError),f++,d.show()):(p.log("notify: chronos creating finally failed",rea.runtime.lastError),r.reject()):(p.log("notify: chronos created",b),d.cancel=()=>{a[b]&&rea.notifications.clear(b,
()=>{})},a[b]=d)})}};r.resolve(d)}else r.resolve();else{const d=()=>{e?k():l--?window.setTimeout(d,200):r.resolve()};d()}};k();return r.promise()})}};return h})(),C=(()=>{const a={};let e=null,f;const g={init:function(){if(f)return f;const h=m=>{e=m||"unknown";p.log("notify: notification level",m)};window.Notification?h(Notification.permission):h("unsupported");return f=w.Pledge()},create:function(h,m,t,c){return g.init().then(()=>{const q=w(),r=()=>{if("granted"==e||"default"==e){const l={nid:null,
cb:{},on:function(k,d){l.cb[k]=d},cancel:function(){},show:function(){const k={body:t||"",icon:h};u.RUNTIME.CHROME&&(43<=u.RUNTIME.BROWSER_VERSION&&void 0!==c.silent&&(k.silent=c.silent),k.requireInteraction=!0);const d=z.createUUID(),n=new window.Notification(m||"",k);n.onclick=()=>{p.log("notify: notification click",d);a[d]&&(a[d].cb.click&&a[d].cb.click(),a[d].cancel(),delete a[d])};n.onclose=n.onerror=b=>{p.log("notify: notification close",d,b);a[d]&&a[d].cb.close&&a[d].cb.close();delete a[d]};
l.cancel=()=>{a[d]&&n.close()};a[d]=l}};q.resolve(l)}else if("denied"==e)q.resolve();else if("unsupported"==e)q.resolve();else{const l=k=>{e="granted"==k?"granted":"denied";r()};u.RUNTIME.SAFARI?Notification.requestPermission(l):Notification.requestPermission().then(l)}};r();return q.promise()})}};return g})(),y={notify:function(a,e,f,g,h){g=g||{};const m=g.timeout;let t=!1;h||(t=!0,h=()=>{});let c=null,q=!1,r=!1,l=null,k;const d=()=>{l&&window.clearTimeout(l);q||h({});r=!0},n=()=>{q=!0;const b={clicked:q};
h&&h(b);c&&c.cancel()};f=f||rea.extension.getURL("images/icon128.png");A.getDataUriFromUrl(f).then(b=>{k=b||f;return w.Pledge()}).then(()=>B.create(k,a,e,g)).then(b=>{if(!b&&window.webkitNotifications)try{const v=window.webkitNotifications.createNotification(k,a||"",e||"");b={on:function(x,D){v["on"+x]=D},cancel:function(){r||v.cancel()},show:function(){v.show()}}}catch(v){p.warn("notify: webkitNotifications creation failed with: "+v.message)}return b}).then(b=>b?b:C.create(k,a,e,g)).then(b=>{b||
(b={cb:{},on:function(v,x){b.cb[v]=x},cancel:function(){},show:function(){t||window.setTimeout(()=>{confirm((a?a+"\n\n":"")+e)?b.cb.click&&b.cb.click():b.cb.close&&b.cb.close()},1)}});return b}).then(b=>{c=b;c.on("close",d);c.on("click",n);l=window.setTimeout(()=>{l=null;c.cancel()},m?m:6E5);p.log("notify:",a,e,f,m);c.show()});return{cancel:function(){c&&c.cancel()}}},showUpdate:function(a,e,f,g){return y.notify(a,e,f,{timeout:3E5},g)},show:function(a,e,f,g,h){return y.notify(a,e,f,g,h)},highlight:function(a,
e){rea.tabs.highlight({tabs:a},e)}};Registry.register("notify","e1582c36",()=>y)});
