'use strict';Registry.require(["helper","i18n"],()=>{const n=Registry.get("helper"),u=Registry.get("i18n");let q;const r=function(){this.name=this.supportURL=this.updateURL=this.downloadURL=this.fileURL=this.icon64=this.icon=this.uuid=null;this.name_i18n={};this.description=this.homepage=this.namespace=this.version=null;this.description_i18n={};this.system=!1;this.enabled=!0;this.position=0;this.grant=[];this.requires=[];this.includes=[];this.matches=[];this.excludes=[];this.resources=[];this.connects=
[];this.blockers=[];this.lastModified=0;this.webRequest=this.version=null;this.sync={imported:!1};this.options={check_for_updates:!0,comment:null,compatopts_for_requires:!0,compat_wrappedjsobject:!1,compat_metadata:!1,compat_foreach:!1,compat_arrayleft:!1,compat_prototypes:!1,compat_uW_gmonkey:!1,compat_forvarin:!1,noframes:null,awareOfChrome:!1,run_at:null,override:{use_includes:[],orig_includes:[],merge_includes:!0,use_matches:[],orig_matches:[],merge_matches:!0,use_excludes:[],orig_excludes:[],
merge_excludes:!0,use_connects:[],merge_connects:!0,use_blockers:[],orig_run_at:null,orig_noframes:null}}},t={init:function(d){q=d},Script:r,processMetaHeader:function(d){const a={};d=d.replace(/\t/g,"    ");d=d.replace(/\r/g,"\n");d=d.replace(/\n\n+/g,"\n");d=d.replace(/[^|\n][ \t]+\/\//g,"//");let f,e;d.split("\n").forEach(h=>{f=h.replace(/^[\t\s]*\/\//gi,"").replace(/^[\t\s]*/gi,"").replace(/\s\s+/gi," ");n.each({"uso:hash":!1,version:!1},(b,l)=>{const m=new RegExp("^@"+l+"[\\t\\s]","i");b=b||
l;-1!=f.search(m)&&(e=f.replace(m,"").replace(/[ \b\r\n]/gi,"").trim(),""!==e&&(a[b]=a[b]||e))})});return a},processHeader:function(d){const a=new r;d=d.replace(/\t/g,"    ");d=d.replace(/\r/g,"\n");d=d.replace(/\n\n+/g,"\n");d=d.replace(/[^|\n][ \t]+\/\//g,"//");let f,e,h,b;d.split("\n").forEach(l=>{h=l.replace(/^[\t\s]*\/\//gi,"").replace(/^[\t\s]*/gi,"");e=h.replace(/\s\s+/gi," ");b=!1;n.each({name:!1,description:!1},(c,g)=>{c=c||g;const k=null!==a[c];if((g=e.match(new RegExp("^@"+g+"(\\[[a-zA-Z_\\-0-9]+\\]|:[a-zA-Z_\\-0-9]+|#[a-zA-Z_\\-0-9]+"+
(k?"| [a-zA-Z_\\-0-9]+":"")+")?[\\t\\s]+(.*)$")))&&3===g.length&&(b=g[2].replace(/[\r\n]/gi,"").trim(),void 0!==b&&""!==b))if(k){var p;c+="_i18n";g[1]&&(p=g[1].match("[a-zA-Z_\\-0-9]+"))&&p[0]&&(p=u.normalizeLocale(p[0]),a[c][p]=b)}else a[c]=b});n.each({version:!1,updateURL:!1,downloadURL:!1,supportURL:!1,homepage:!1,homepageURL:"homepage",website:"homepage",source:"homepage",uuid:!1},(c,g)=>{const k=new RegExp("^@"+g+"[\\t\\s]","i");c=c||g;-1!=e.search(k)&&(b=e.replace(k,"").replace(/[ \b\r\n]/gi,
"").trim(),""!==b&&(a[c]=a[c]||b))});n.each({icon:!1,iconURL:"icon",defaulticon:"icon",icon64:!1,iconURL64:"icon64"},(c,g)=>{const k=new RegExp("^@"+g+"[\\t\\s]","i");c=c||g;-1!=e.search(k)&&(b=e.replace(k,"").replace(/[\b\r\n]/gi,"").trim(),""!==b&&(a[c]=a[c]||b))});n.each({namespace:!1,author:!1,copyright:!1},(c,g)=>{const k=new RegExp("^@"+g+"[\\t\\s]","i");c=c||g;-1!=h.search(k)&&(b=h.replace(k,"").replace(/[\b\r\n]/gi,"").trim(),""!==b&&(a[c]=a[c]||b))});n.each({"run-at":"run_at"},(c,g)=>{const k=
new RegExp("^@"+g+"[\\t\\s]","i");c=c||g;-1!=e.search(k)&&(b=e.replace(k,"").replace(/[\r\n]/gi,"").trim(),""!==b&&(a.options[c]=a.options[c]||b))});const m=c=>c.trim().replace(/ /gi,"%20").replace(/[\b\r\n]/gi,"");n.each({include:"includes",match:"matches",exclude:"excludes",connect:"connects","connect-src":"connects",domain:"connects"},(c,g)=>{const k=new RegExp("^@"+g+"[\\t\\s]","i");c=c||g;-1!=e.search(k)&&(b=m(e.replace(k,"")).trim())&&a[c].push(b)});-1!=e.search(/^@require[\t\s]/)&&(b=m(e.replace(/^@require[\t\s]*/gi,
"")).trim())&&a.requires.push({url:b,loaded:!1,textContent:""});if(-1!=e.search(/^@resource[\t\s]/)&&(b=e.replace(/^@resource[\t\s]*/gi,"").trim(),f=b.split(" "),2<=f.length)){l=f.shift();const c=m(f.join(" "));""!==l&&c&&a.resources.push({name:l,url:c,loaded:!1})}-1!=e.search(/^@grant[\t\s]/)&&(b=e.replace(/^@grant/gi,"").replace(/[\b\r\n]/gi,"").trim())&&a.grant.push(b);n.each({noframes:!1,nocompat:"awareOfChrome"},(c,g)=>{c=c||g;-1!=e.search(new RegExp("^@"+g+"[\\t\\s\\r\\n]?"))&&(a.options[c]=
!0)});if(-1!=e.search(/^@webRequest[\t\s]/)&&(b=e.replace(/^@webRequest/gi,"").replace(/[\b\r\n]/gi,"").trim())){let c;try{c=JSON.parse(b),a.webRequest=(a.webRequest||[]).concat(c instanceof Array?c:[c])}catch(g){return console.warn("parser: unable to process webRequest header",b),new r}}});a.version||(a.version="0.0");return a},getHeaderTags:function(){return{start:"==UserScript==",stop:"==/UserScript=="}},getHeader:function(d){const a=n.getStringBetweenTags(d,"==UserScript==","==/UserScript==");
if(!a)return null;const f=d.indexOf("==UserScript=="),e=d.indexOf("<html>");d=d.indexOf("<body>");return 0<e&&e<f||0<d&&d<f?null:a},createScriptFromSrc:function(d){d=(d||"").replace(/(\r\n|\n|\r)/gm,"\n");const a=t.getHeader(d);if(!a)return{};const f=t.processHeader(a);f.textContent=d;f.header=a;f.options.awareOfChrome||(f.options.compat_wrappedjsobject=d!=q.unWrappedJsObjectify(d),f.options.compat_metadata=d!=q.unMetaDataify(d),f.options.compat_prototypes=q.findPrototypes(d));-1!=d.indexOf("unsafeWindow.gmonkey")&&
(f.options.compat_uW_gmonkey=!0);return f},versionCmp:(()=>{const d=f=>{f=f.split(".");return f.slice(0,3).concat([f.slice(3).join(".")]).concat([0,0,0,0]).slice(0,4).map(e=>{e=e.toString().match(/((?:\-?[0-9]+)?)([^0-9\-]*)((?:\-?[0-9]+)?)(.*)/);return[Number(e[1]),e[2],Number(e[3]),e[4]]}).reduce((e,h)=>e.concat(h))},a=(f,e)=>{f=Array.isArray(f)?f:d(f);e=Array.isArray(e)?e:d(e);for(let l=0;16>l;l++){var h=f[l],b=e[l];if(1===l%2){if(!h&&b)return a.eNEWER;if(h&&!b)return a.eOLDER;h=h.match(/\w/g)||
[];b=b.match(/\w/g)||[];for(let m=0;m<Math.min(h.length,b.length);m++){if(h[m].charCodeAt(0)>b[m].charCodeAt(0))return a.eNEWER;if(h[m].charCodeAt(0)<b[m].charCodeAt(0))return a.eOLDER}if(h.length>b.length)return a.eNEWER;if(h.length<b.length)return a.eOLDER}else{if(Number(h)>Number(b))return a.eNEWER;if(Number(h)<Number(b))return a.eOLDER}}return a.eEQUAL};a.__proto__.eERROR=-2;a.__proto__.eOLDER=-1;a.__proto__.eEQUAL=0;a.__proto__.eNEWER=1;return a})()};Registry.register("parser","e1582c36",
t)});
