'use strict';Registry.require(["promise","helper","convert"],()=>{const q=Registry.get("promise"),B=Registry.get("helper"),t=Registry.get("convert");let C=()=>{const h=q();Registry.vendor(["vendor/jszip/jszip"],()=>{C=q.Pledge;h.resolve()});return h.promise()};const u=(()=>{let h,m=!1,n;const e=()=>{const a=q();return n=a};return{write:function(){const a=q();m=!1;h=new JSZip;a.resolve(h);return a.promise()},open:function(a){const b=e();m=!0;JSZip.loadAsync(a).then(c=>{h=c;b.resolve(h)},c=>{n&&n.reject(c);
b.reject(c)});return b.promise()},entries:function(){const a=e(),b=h.files;a.resolve(Object.keys(b).map(c=>{if((c=b[c])&&!c.dir)return{filename:c.name}}).filter(c=>c));return a.promise()},get:function(a){const b=e();h.file(a.filename).async("arraybuffer").then(c=>{b.resolve(c)});return b.promise()},put:function(a,b,c){const l=e();try{h.file(a,b,{date:c?new Date(c):void 0}),l.resolve()}catch(r){l.reject(r)}return l.promise()},end:function(){const a=e();m?a.resolve():h.generateAsync({type:"blob",compression:"DEFLATE",
comment:"Created by Tampermonkey"}).then(b=>{a.resolve(b)},b=>{a.reject(b)});return a.promise()}}})();Registry.register("porter","e1582c36",{zip:{create:function(h,m){const n=q();let e=0;C().then(()=>u.write()).then(a=>{const b=q(),c={},l=(d,p)=>{let f=[d,p].join(".");if(c[f]){let k;do k=d+" ("+c[f]+")",f=[k,p].join("."),c[f]++;while(c[f]);return l(k,p)}c[f]=1;return f},r=h.length,g=()=>{if(!h.length)return b.resolve();const d=h.shift(),p=d.meta.name.replace(/[\\\/$*?|]/g,"-"),f=l(p,"user.js"),
k=l(p,"options.json"),y=l(p,"storage.json"),z=JSON.stringify({options:d.options,settings:d.settings,meta:d.meta}),v=d.storage?JSON.stringify(d.storage):null;e+=d.source.length;console.log("porter: add to zip",f,e);n.notify("Zip: "+Math.floor((r-h.length)/r*100)+"%");u.put(f,d.source,d.meta.modified).then(()=>{e+=z.length;console.log("porter: add to zip",k,e);return u.put(k,z)}).then(()=>{if(!v)return q.Pledge();e+=v.length;console.log("porter: add to zip",y,e);return u.put(y,v)}).then(()=>{if(!d.resources.length&&
!d.requires.length)return q.Pledge();const w=[];["resources","requires"].forEach(A=>{d[A].forEach((x,D)=>{if(void 0!==x.source){D=x.meta.name.replace(/[\\\/$*?|]/g,"-");var F=t.MD5(A+x.meta.url),E=[f,F,D].join("-"),G=JSON.stringify(x.meta);x=t.str2arrbuf(x.source,"resources"==A?void 0:"UTF-8");w.push(u.put(E,x).then(()=>u.put(E+"."+A+".json",G)))}})});return q.when(w)}).fail(w=>{console.log("porter: add to zip failed",w)}).always(()=>{console.log("porter: add to zip -> next round");window.setTimeout(g,
5)})};g();return b.promise()}).then(()=>{console.log("porter: add global props");return m?u.put("Tampermonkey.global.json",JSON.stringify(m)):q.Pledge()}).then(()=>u.end()).done(a=>{n.resolve(a)}).fail(()=>{n.reject()});return n.promise()},read:function(h){const m=q();let n;C().then(()=>u.open(h)).then(()=>u.entries()).then(e=>{const a=q(),b={},c={},l=e.length,r=()=>{if(e.length){const g=e.shift();console.log("porter: read from zip",g.filename);u.get(g).done(d=>{let p=g.filename.match(/((.*)\.(storage\.json)|(.*)\.(options\.json)|(.*)\.(global\.json)|(.*)\.(user\.js)|(.*)\.user\.js-[0-9a-f]+-.*\.(resources\.json)|(.*)\.user\.js-[0-9a-f]+-.*\.(requires\.json))$/);
p&&(p=p.slice(1).filter(f=>f));if(!p||3>p.length)c[g.filename]=d;else try{const f=p[1],k=p[2];b[f]=b[f]||{resources:{},requires:{}};d=t.arrbuf2str(d,"UTF-8");"global.json"==k?n=JSON.parse(d):"user.js"==k?b[f].source=d:"options.json"==k?b[f].options=JSON.parse(d):"resources.json"==k?b[f].resources[g.filename]={name:g.filename,data:JSON.parse(d)}:"requires.json"==k?b[f].requires[g.filename]={name:g.filename,data:JSON.parse(d)}:"storage.json"==k&&(b[f].storage=JSON.parse(d))}catch(f){console.warn("porter: read from zip failed",
f)}}).always(()=>{m.notify("Zip: "+Math.floor((l-e.length)/l*100)+"%");window.setTimeout(r,5)})}else{const g=[];B.each(b,(d,p)=>{const f=d.options||{};f.source=d.source;f.storage=d.storage;["resources","requires"].forEach(k=>{const y=d[k];y&&B.each(y,(z,v)=>{let w;v=z.name.replace("."+k+".json","");if(w=c[v])f[k]=v=f[k]||[],v.push({meta:z.data,source:t.arrbuf2str(w,"resources"==k?void 0:"UTF-8")})})});g.push(f)});a.resolve({scripts:g,global_settings:n})}};r();return a.promise()}).done(e=>{m.resolve(e)}).fail(()=>
{m.reject()});return m.promise()}},json:{create:function(h,m){const n=q(),e={created_by:"Tampermonkey",version:"1",scripts:[],settings:m};h.forEach(a=>{const b={name:a.meta.name,options:a.options,storage:a.storage,enabled:a.settings.enabled,position:a.settings.position,file_url:a.meta.file_url,uuid:a.meta.uuid,source:t.Base64.encode(t.UTF8.encode(a.source))};["resources","requires"].forEach(c=>{const l=a[c];if(l&&l.length){var r=b[c]=[];l.forEach((g,d)=>{void 0!==g.source&&(d=g.meta,g=t.Base64.encode(t.UTF8.encode(g.source)),
r.push({meta:d,source:g}))})}});e.scripts.push(b)});n.resolve(JSON.stringify(e));return n.promise()},read:function(h){const m=q(),n=e=>{if(e.trim()){var a=null;try{return a=JSON.parse(e),a.scripts=B.map(a.scripts,b=>{const c={meta:{uuid:b.uuid,name:b.name,file_url:b.file_url},settings:{enabled:b.enabled,position:b.position},options:b.options,storage:b.storage,source:t.UTF8.decode(t.Base64.decode(b.source))};["resources","requires"].forEach(l=>{const r=b[l];r&&r.length&&(c[l]=r.map(g=>({meta:g.meta,
source:t.UTF8.decode(t.Base64.decode(g.source))})))});return c}),m.resolve({scripts:a.scripts,global_settings:a.settings})}catch(b){if(-1!=e.indexOf("<body>")){a=e.indexOf("<body>");const c=e.lastIndexOf("</body>");if(-1!=a&&-1!=c)return e=e.substr(a+6,c-(a+6)),n(e)}}}m.reject()};n(h);return m.promise()}}})});
