'use strict';(()=>{Registry.require(["promise"],()=>{const t=rea.FEATURES,m=Registry.get("promise"),F=[];let v=!0;const A=(()=>{const a=[t.CONSTANTS.STORAGE.VERSION,t.CONSTANTS.STORAGE.TYPE],c={};a.forEach(e=>{c[e]=!0});return{keys:a,has:function(e){return!!c[e]}}})(),x=t.HTML5.LOCALSTORAGE,G=()=>rea.other.openDatabase("tmStorage","1.0","TM Storage",31457280),B=(a,c)=>{if(!a)return c;const e=a[0];a=a.substring(1);switch(e){case "b":return"true"==a;case "n":return Number(a);case "o":try{return JSON.parse(a)}catch(f){console.error("Storage: getValue ERROR: "+
f.message)}return c;default:return a}},C=a=>{const c=(typeof a)[0];switch(c){case "o":try{a=c+JSON.stringify(a)}catch(e){console.error("Storage: setValue ERROR: "+e.message);return}break;default:a=c+a}return a},z=function(a,c){const e=m();var f=Array.prototype.slice.call(arguments,2);let l;"string"==typeof a?a==t.DB.USE&&"clean"==c?console.warn("Storage: can't clean currently active storage"):l=u.implementations[a][c]:l=a[c];if(l)if(f=l.apply(this,f),"object"===typeof f&&f.then)f.then(function(){e.resolve.apply(this,
arguments)},k=>{e.reject()});else return f;else e.resolve();return e.promise()},D=(a,c)=>{const e=m(),f=[];Object.getOwnPropertyNames(c).forEach(l=>{void 0!==c[l]&&f.push(z(a,"setValue",l,c[l]))});m.when(f).done(()=>{e.resolve()});return e.promise()},E=(a,c)=>{const e={};c.forEach(f=>{e[f]=z(a,"getValue",f)});return e};var u={secure:{cookie:(()=>{const a=f=>{document.cookie="s_"+f+"=;expires=Thu, 01 Jan 1970 00:00:00 UTC;path=/"},c=()=>{const f=document.cookie.split(";"),l=[];for(let d=0;d<f.length;d++){var k=
f[d].trim();const g=k.indexOf("=");k=k.substr(0,g);"s_"==k.substr(0,2)&&l.push(k.substr(2))}return l},e={setValue:function(f,l){const k=m();l=C(l);var d=new Date;d.setTime(d.getTime()+47304E7);d="expires="+d.toUTCString();document.cookie="s_"+f+"="+l+";"+d+";path=/";k.resolve();return k.promise()},setValues:function(f){const l=[];Object.keys(f).forEach(k=>{l.push(e.setValue(k,f[k]))});return m.sidebyside(l)},getValue:function(f,l){a:{f="s_"+f+"=";const k=document.cookie.split(";");for(let d=0;d<k.length;d++){let g=
k[d];for(;" "==g.charAt(0);)g=g.substring(1);if(0==g.indexOf(f)){f=g.substring(f.length,g.length);break a}}f=null}return B(f,l)},deleteAll:function(){const f=m();e.listValues().forEach(l=>{a(l)});f.resolve();return f.promise()},deleteValue:function(f){const l=m();a(f);l.resolve();return l.promise()},listValues:function(){return c().map(f=>f)}};return e})()},implementations:{localStorage:(()=>{const a={setValue:function(c,e){const f=m();e=C(e);v&&x.setItem(c,e);f.resolve();return f.promise()},setValues:function(c){const e=
[];Object.keys(c).forEach(f=>{e.push(a.setValue(f,c[f]))});return m.sidebyside(e)},getValue:function(c,e){return B(x.getItem(c,e),e)},deleteAll:function(){const c=m();v&&a.listValues().forEach(e=>{A.has(e)||x.removeItem(e)});c.resolve();return c.promise()},deleteValue:function(c){const e=m();v&&x.removeItem(c);e.resolve();return e.promise()},listValues:function(){const c=[];for(let e=0;e<x.length;e++)c.push(x.key(e));return c}};return{options:{},methods:a}})(),sql:(()=>{let a=null,c=null;const e=
()=>{const k=m();c.db.transaction(d=>{d.executeSql("CREATE TABLE IF NOT EXISTS config(ID INTEGER PRIMARY KEY ASC, name TEXT, value TEXT)",[],k.resolve,c.onError)});return k.promise()},f=()=>{const k=m();c={db:G(),onSuccess:function(d,g){},onError:function(d,g){console.error("webSQL: localDB Error ",g)}};c.db?e().done(k.resolve):(c=null,k.reject());return k.promise()},l={setValue:function(k,d){const g=m(),p=C(d);v&&(a[k]?c.db.transaction(b=>{b.executeSql("UPDATE config SET value=? WHERE name=?",[p,
k],()=>{rea.runtime.lastError&&console.warn(rea.runtime.lastError);g.resolve()},c.onError)}):c.db.transaction(b=>{b.executeSql("INSERT INTO config(name, value) VALUES (?,?)",[k,p],()=>{rea.runtime.lastError&&console.warn(rea.runtime.lastError);g.resolve()},c.onError)}));a[k]=p;v||g.resolve();return g.promise()},setValues:function(k){const d=[];Object.keys(k).forEach(g=>{d.push(l.setValue(g,k[g]))});return m.sidebyside(d)},getValue:function(k,d){return B(a[k],d)},deleteAll:function(){const k=m(),d=
E(l,A.keys);a=d;v?c.db.transaction(g=>{g.executeSql("DROP TABLE config",[],()=>{e().done(()=>{D(l,d).done(k.resolve)})},c.onError)}):k.resolve();return k.promise()},deleteValue:function(k){const d=m();delete a[k];v?c.db.transaction(g=>{g.executeSql("DELETE FROM config WHERE name=?",[k],d.resolve,c.onError)}):d.resolve();return d.promise()},listValues:function(){const k=[];Object.getOwnPropertyNames(a).forEach(d=>{k.push(d)});return k},isWorking:function(){return m.Pledge()}};return{init:function(){const k=
m(),d=(p,b)=>{a={};if(b)for(p=0;p<b.rows.length;p++)a[b.rows.item(p).name]=b.rows.item(p).value;k.resolve()},g=()=>{a?k.resolve():c.db.transaction(p=>{p.executeSql("SELECT * FROM config",[],d,c.onError)})};c?g():f().done(g).fail(k.reject);return k.promise()},clean:function(){a=null;return m.Pledge()},options:{},methods:l}})(),chromeStorage:(()=>{let a=null,c=!1,e=!1;const f=rea.extension.inIncognitoContext?"incognito":"normal",l=(d,g)=>{v&&e&&"local"==g&&d&&Object.keys(d).forEach(p=>{const b=d[p];
b.newValue?b.newValue.origin!==f&&(a[p]=b.newValue.value,u.notifyDifferentOriginChangeListeners(p,b.newValue)):b.oldValue&&b.oldValue.origin!==f&&delete a[p]})},k={setValue:function(d,g){const p=m();a[d]=g;if(v){const b={};b[d]={origin:f,value:g};rea.storage.local.set(b,p.resolve)}else p.resolve();return p.promise()},setValues:function(d){const g=m(),p={};Object.keys(d).forEach(b=>{const h=d[b];a[b]=h;v&&(p[b]={origin:f,value:h})});v?rea.storage.local.set(p,g.resolve):g.resolve();return g.promise()},
getValue:function(d,g){return void 0===a[d]?g:a[d]},deleteAll:function(){const d=m(),g=E(k,A.keys);a=g;v?rea.storage.local.clear(()=>{D(k,g).done(d.resolve)}):d.resolve();return d.promise()},deleteValue:function(d){const g=m();delete a[d];v?rea.storage.local.remove(d,g.resolve):g.resolve();return g.promise()},listValues:function(){const d=[];Object.getOwnPropertyNames(a).forEach(g=>{d.push(g)});return d},setTemporary:function(d){v=!d;e=!0},isSupported:function(){return m.Pledge()},isWorking:function(){const d=
m();let g=0;const p=Date.now(),b={};b.foo=p;const h=q=>{5>=++g?(console.warn("storage:",q?q:"storage set/get test failed!"),window.setTimeout(r,g*g*100)):(console.warn("storage: storage set/get test finally failed!"),n&&(window.clearTimeout(n),n=null,d.reject()))};var n=window.setTimeout(()=>{n=null},18E4),r=()=>{console.log("Storage: test -> start");const q=Date.now();rea.storage.local.set(b,()=>{console.log("Storage: test -> set after "+(Date.now()-q)+"ms");rea.storage.local.get("foo",w=>{console.log("Storage: test -> get after "+
(Date.now()-q)+"ms");if(w){if(w.foo!==p)return h("read value is different "+JSON.stringify(w.foo)+" != "+JSON.stringify(p));if(rea.runtime.lastError)return h(rea.runtime.lastError&&rea.runtime.lastError.message||"lastError is set")}else return h("read value is"+w);rea.storage.local.remove("foo",()=>{console.log("Storage: test -> remove after "+(Date.now()-q)+"ms");n&&(window.clearTimeout(n),n=null,d.resolve())})})})};r();return d.promise()}};return{init:function(){const d=m();a?d.resolve():rea.storage.local.get(null,
g=>{a={};g&&Object.keys(g).forEach(p=>{const b=g[p];a[p]=b&&b.hasOwnProperty("origin")&&b.hasOwnProperty("value")?b.value:b});c||(rea.storage.onChanged.addListener(l),c=!0);d.resolve()});return d.promise()},clean:function(){const d=m();a=null;d.resolve();return d.promise()},options:{},methods:k}})(),file:(()=>{let a=null,c=null;const e=()=>{const b=m(),h=n=>{console.warn("fileStorage: listFiles() error:",n);b.reject()};c.root.getDirectory("data",{create:!0},n=>{const r=n.createReader();let q=[];const w=
()=>{r.readEntries(y=>{y.length?(q=q.concat(y),w()):b.resolve(q)},h)};w()},h);return b.promise()},f=(b,h)=>{const n=m(),r=q=>{console.warn("fileStorage: writeFileData(",b,") error:",q);n.reject()};c.root.getDirectory("data",{create:!0},q=>{q.getFile(b,{create:!0},w=>{w.createWriter(y=>{y.onwriteend=H=>{y.onwriteend=I=>{n.resolve()};y.onerror=r;H=new Blob([h],{type:"text/plain"});y.write(H)};y.truncate(0)},r)},r)},r);return n.promise()},l=b=>{const h=m(),n=q=>{console.warn("fileStorage: getFileData(",
b,") error:",q);h.reject()},r=q=>{const w=new FileReader;w.onloadend=function(){h.resolve(this.result)};w.onerror=n;w.onabort=n;w.readAsText(q)};c.root.getDirectory("data",{create:!0},q=>{q.getFile(b,{},w=>{w.file(y=>{r(y)},n)},n)},n);return h.promise()},k=b=>{const h=m(),n=r=>{console.warn("fileStorage: deleteFile(",b,") error:",r);h.reject()};c.root.getDirectory("data",{create:!0},r=>{r.getFile(b,{create:!1},q=>{q.remove(h.resolve,n)},n)},n);return h.promise()},d=()=>{const b=m(),h=n=>{console.warn("fileStorage: removeDir() error:",
n);b.reject()};c.root.getDirectory("data",{create:!0},n=>{n.removeRecursively(b.resolve,h)},h);return b.promise()},g=()=>{const b=m();a={};const h=[];e().done(n=>{n.forEach(r=>{"string"!==typeof r&&(r=r.name);h.push(l(r).always(q=>{a[r]=q}))});m.when(h).always(()=>{b.resolve()})}).fail(b.resolve);return b.promise()},p={isSupported:function(){const b=m();window.File&&window.FileReader&&window.FileList&&window.Blob?b.resolve():b.reject();return b.promise()},isWorking:function(){return m.Pledge()},setValue:function(b,
h){const n=m();h=C(h);a[b]=h;v?f(b,h).always(n.resolve):n.resolve();return n.promise()},setValues:function(b){const h=[];Object.keys(b).forEach(n=>{h.push(p.setValue(n,b[n]))});return m.sidebyside(h)},getValue:function(b,h){return B(a[b],h)},deleteAll:function(){const b=m(),h=E(p,A.keys);a=h;v?d().always(()=>{D(p,h).always(b.resolve)}):b.resolve();return b.promise()},deleteValue:function(b){const h=m();delete a[b];v?k(b).always(h.resolve):h.resolve();return h.promise()},listValues:function(){const b=
[];Object.getOwnPropertyNames(a).forEach(h=>{b.push(h)});return b}};return{init:()=>{const b=m();a?b.resolve():rea.other.requestFileSystem(window.PERSISTENT,31457280,h=>{c=h;g().done(b.resolve)},h=>{h&&console.warn("fileStorage: ",h);b.reject()});return b.promise()},clean:function(){a=null;return m.Pledge()},options:{},methods:p}})()},migrate:function(a,c,e){const f=m(),l=u.implementations[a],k=u.implementations[c];e=e||{};l&&k?z(a,"init").then(()=>z(c,"init")).then(()=>{const d=m(),g=[];l.methods.listValues().forEach(p=>
{const b=l.methods.getValue(p);e.drop&&g.push(l.methods.deleteValue(p));g.push(k.methods.setValue(p,b))});m.when(g).done(()=>{d.resolve()});return d.promise()}).then(()=>z(c,"clean")).then(()=>z(a,"clean")).done(()=>{f.resolve()}).fail(()=>{f.reject()}):(console.error("Migration: unknown storage implementation(s) ",a,c),f.reject());return f.promise()},isSupported:function(){return m.Pledge()},isWorking:function(){return m.Pledge()},setTemporary:function(a){v=!a},init:function(){console.debug("Storage: use "+
t.DB.USE);Object.getOwnPropertyNames(u.implementations[t.DB.USE].methods).forEach(a=>{Object.defineProperty(u,a,{get:()=>u.implementations[t.DB.USE].methods[a],enumerable:!0})});return u.implementations[t.DB.USE].init?u.implementations[t.DB.USE].init():m.Pledge()},getValues:function(a,c){const e={};c||(c={});Object.getOwnPropertyNames(a).forEach(f=>{e[f]=u.implementations[t.DB.USE].getValue(f,c[f])});return e},factoryReset:function(){x&&x.removeItem(t.CONSTANTS.STORAGE.LEGACY_VERSION);return u.deleteAll()},
isWiped:function(){if("localStorage"===t.DB.USE||!x)return m.Pledge(!1);const a=m(),c=u.getValue(t.CONSTANTS.STORAGE.VERSION);let e=!1;x.getItem(t.CONSTANTS.STORAGE.LEGACY_VERSION)&&!c&&(u.listValues().length?console.warn("storage: unable to find version information"):e=!0);a.resolve(e);return a.promise()},setVersion:function(a,c){const e=m();v?(x&&x.setItem(t.CONSTANTS.STORAGE.LEGACY_VERSION,a),u.setValue(t.CONSTANTS.STORAGE.VERSION,a).then(()=>c?u.setValue(t.CONSTANTS.STORAGE.SCHEMA,c):m.Pledge()).always(e.resolve)):
e.resolve();return e.promise()},getVersion:function(a){const c=m();let e=u.getValue(t.CONSTANTS.STORAGE.VERSION)||u.getValue(t.CONSTANTS.STORAGE.LEGACY_VERSION)||(x?x.getItem(t.CONSTANTS.STORAGE.LEGACY_VERSION):null);e?c.resolve(e):z("sql","init").then(f=>{e=u.implementations.sql.methods.getValue(t.CONSTANTS.STORAGE.LEGACY_VERSION)||a;return z("sql","clean")}).always(()=>{c.resolve(e||a)});return c.promise()},getSchemaVersion:function(){return u.getValue(t.CONSTANTS.STORAGE.SCHEMA,"3.5")},addDifferentOriginChangeListener:function(a,
c){F.push({search:a,cb:c})},notifyDifferentOriginChangeListeners:function(a,c){F.forEach(e=>{0==a.indexOf(e.search)&&e.cb(a,c)})},recover:function(a,c){"string"===typeof a&&(a={method:a,storages:["sql","chromeStorage"]});const e={};a.storages.forEach(f=>{e[f]=!0});if("log"==a.method){let f=null,l,k;const d=[{method:"sql",fn:function(b){console.debug("check sql storage for data...");try{k=G();if(rea.runtime.lastError||!k)return f=rea.runtime.lastError,b();k.transaction(h=>{h.executeSql("CREATE TABLE IF NOT EXISTS config(ID INTEGER PRIMARY KEY ASC, name TEXT, value TEXT)",
[],()=>{console.debug("sql table found/created");b()},(n,r)=>{f=r;b()})})}catch(h){f=h,window.setTimeout(b,1)}}},{method:"sql",fn:function(b){const h={};k.transaction(n=>{n.executeSql("SELECT * FROM config",[],(r,q)=>{if(q)for(r=0;r<q.rows.length;r++)h[q.rows.item(r).name]=q.rows.item(r).value;l=h;window.setTimeout(b,1)},(r,q)=>{f=q;b()})})}},{method:"sql",fn:function(b){const h=l?Object.getOwnPropertyNames(l):[];l&&h.length?(console.debug("found values:"),h.forEach(n=>{console.debug("    ",n,l[n]&&
30<l[n].length?l[n].substr(0,30):l[n])})):(console.warn("no data found"),e.sql=!1);window.setTimeout(b,1)}},{method:"chromeStorage",fn:function(b){console.debug("check chromeStorage for data...");rea.storage.local.get(null,h=>{l=h;b()})}},{method:"chromeStorage",fn:function(b){const h=l?Object.getOwnPropertyNames(l):[];l&&h.length?(console.debug("found values:"),h.forEach(n=>{console.debug("    ",n,l[n]&&30<l[n].length?l[n].substr(0,30):l[n])})):(console.warn("no data found"),e.chromeStorage=!1,window.setTimeout(b,
1))}}];let g=0;const p=()=>{if(f)console.warn("error:",f);else for(;d[g];){if(e[d[g].method]){d[g].fn(p);g++;return}g++}c&&c()};p()}}};Registry.register("storage","e1582c36",()=>u)})})();
